// 怪物掉落表 - 依据原服务端 Envir/MonItems/ 爆率数据配置（通天塔Boss档为自拟梯度）
// 格式: { item: 物品名, chance: 概率分母(1/N), count: 数量(可选) }
const DROPS = {
  '半兽人': [
    { item: '金币', chance: 2, count: 40 },
    { item: '金币', chance: 10000, count: 400 },
    { item: '青铜剑', chance: 1800 }, { item: '小手镯', chance: 1800 },
    { item: '玻璃戒指', chance: 1800 }, { item: '六角戒指', chance: 1800 },
    { item: '皮制手套', chance: 1800 }, { item: '银手镯', chance: 1800 },
    { item: '钢手镯', chance: 1800 }, { item: '牛角戒指', chance: 1800 },
    { item: '大手镯', chance: 1800 }, { item: '青铜头盔', chance: 1800 },
    { item: '白玉戒指', chance: 1800 },
    { item: '布衣', chance: 300 },
    { item: '木剑', chance: 600 }, { item: '匕首', chance: 600 },
    { item: '乌木剑', chance: 600 }, { item: '金项链', chance: 600 },
    { item: '古铜戒指', chance: 600 }, { item: '铁手镯', chance: 600 },
    { item: '传统项链', chance: 600 },
  ],
  '僵尸1': [
    { item: '金币', chance: 2, count: 100 },
    { item: '金币', chance: 5000, count: 300 },
    { item: '金创药(中量)', chance: 500 }, { item: '魔法药(中量)', chance: 500 },
    { item: '抗拒火环', chance: 600 }, { item: '精神力战法', chance: 600 },
    { item: '火球术', chance: 600 }, { item: '治愈术', chance: 600 },
    { item: '基本剑术', chance: 600 },
    { item: '施毒术', chance: 2400 }, { item: '攻杀剑术', chance: 2400 },
    { item: '诱惑之光', chance: 2400 }, { item: '瞬息移动', chance: 2400 },
    { item: '隐身术', chance: 2400 }, { item: '大火球', chance: 2400 },
    { item: '召唤骷髅', chance: 2400 }, { item: '雷电术', chance: 2400 },
    { item: '地狱火', chance: 2400 }, { item: '灵魂火符', chance: 2400 },
    { item: '疾光电影', chance: 6000 }, { item: '刺杀剑术', chance: 6000 },
    { item: '火墙', chance: 6000 },
    { item: '幽灵盾', chance: 6000 }, { item: '心灵启示', chance: 6000 },
    { item: '集体隐身术', chance: 6000 },
    { item: '神圣战甲术', chance: 6000 }, { item: '爆裂火焰', chance: 6000 },
    { item: '祈祷之刃', chance: 20000 }, { item: '祈祷手镯', chance: 20000 },
    { item: '祈祷项链', chance: 20000 }, { item: '祈祷戒指', chance: 20000 },
    { item: '祈祷头盔', chance: 20000 },
  ],
  '蜈蚣': [
    { item: '金币', chance: 4, count: 100 },
    { item: '金币', chance: 10000, count: 1000 },
    { item: '太阳水', chance: 40 },
    { item: '祝福油', chance: 4800 },
    { item: '死神手套', chance: 5000 }, { item: '蓝翡翠项链', chance: 5000 },
    { item: '金手镯', chance: 5000 }, { item: '道德戒指', chance: 5000 },
    { item: '魅力戒指', chance: 5000 }, { item: '放大镜', chance: 5000 },
    { item: '竹笛', chance: 5000 }, { item: '道士头盔', chance: 5000 },
    { item: '凝霜', chance: 5000 }, { item: '珊瑚戒指', chance: 5000 },
    { item: '骷髅头盔', chance: 5000 }, { item: '修罗', chance: 5000 },
    { item: '降妖除魔戒指', chance: 5000 }, { item: '金戒指', chance: 5000 },
    { item: '紫绸靴', chance: 5000 }, { item: '青铜腰带', chance: 5000 },
    { item: '金萤帽', chance: 5000 }, { item: '金铜头盔', chance: 5000 },
    { item: '青雷', chance: 5000 }, { item: '灵力项链', chance: 5000 },
    { item: '黑铁手镯', chance: 5000 }, { item: '火血匕', chance: 5000 },
    { item: '灵魂战衣', chance: 2500 },
    { item: '重盔甲', chance: 2500 },
    { item: '灵魂战衣', chance: 2500 },
    { item: '魔法长袍', chance: 2500 },
    { item: '道士手镯', chance: 2500 }, { item: '黑檀手镯', chance: 2500 },
    { item: '降魔', chance: 2500 }, { item: '斩马刀', chance: 2500 },
    { item: '偃月', chance: 2500 }, { item: '生铁戒指', chance: 2500 },
    { item: '黑色水晶戒指', chance: 2500 }, { item: '蛇眼戒指', chance: 2500 },
    { item: '珍珠戒指', chance: 2500 }, { item: '破魂', chance: 2500 },
    { item: '白色虎齿项链', chance: 2500 }, { item: '白金项链', chance: 2500 },
    { item: '骷髅戒指', chance: 2500 }, { item: '鹿皮靴', chance: 2500 },
    { item: '铁腰带', chance: 2500 },
    { item: '八荒', chance: 1200 }, { item: '半月', chance: 1200 },
    { item: '海魂', chance: 1200 }, { item: '凌风', chance: 1200 },
    { item: '中型盔甲', chance: 600 },
    { item: '铁剑', chance: 500 }, { item: '短剑', chance: 500 },
    { item: '轻型盔甲', chance: 250 },
    { item: '青铜剑', chance: 500 }, { item: '小手镯', chance: 500 },
    { item: '玻璃戒指', chance: 500 }, { item: '六角戒指', chance: 500 },
  ],
  '红野猪': [
    { item: '金币', chance: 3, count: 150 },
    { item: '金币', chance: 10000, count: 1200 },
    { item: '金创药(中量)', chance: 15 }, { item: '魔法药(中量)', chance: 25 },
    { item: '太阳水', chance: 50 },
    { item: '祝福油', chance: 4800 },
    { item: '死神手套', chance: 11200 }, { item: '蓝翡翠项链', chance: 11200 },
    { item: '金手镯', chance: 11200 }, { item: '道德戒指', chance: 11200 },
    { item: '凝霜', chance: 11200 }, { item: '珊瑚戒指', chance: 11200 },
    { item: '骷髅头盔', chance: 11200 }, { item: '修罗', chance: 11200 },
    { item: '降妖除魔戒指', chance: 11200 }, { item: '金戒指', chance: 11200 },
    { item: '紫绸靴', chance: 11200 }, { item: '青铜腰带', chance: 11200 },
    { item: '金萤帽', chance: 11200 }, { item: '金铜头盔', chance: 11200 },
    { item: '青雷', chance: 11200 }, { item: '灵力项链', chance: 11200 },
    { item: '黑铁手镯', chance: 11200 }, { item: '火血匕', chance: 11200 },
    { item: '灵魂战衣', chance: 5600 },
    { item: '重盔甲', chance: 5600 },
    { item: '灵魂战衣', chance: 5600 },
    { item: '魔法长袍', chance: 5600 },
    { item: '道士手镯', chance: 1400 }, { item: '黑檀手镯', chance: 1400 },
    { item: '降魔', chance: 1400 }, { item: '斩马刀', chance: 1400 },
    { item: '偃月', chance: 1400 }, { item: '生铁戒指', chance: 1400 },
    { item: '黑色水晶戒指', chance: 1400 }, { item: '蛇眼戒指', chance: 1400 },
    { item: '珍珠戒指', chance: 1400 }, { item: '破魂', chance: 1400 },
    { item: '白色虎齿项链', chance: 1400 }, { item: '白金项链', chance: 1400 },
    { item: '骷髅戒指', chance: 1400 }, { item: '鹿皮靴', chance: 1400 },
    { item: '铁腰带', chance: 1400 },
    { item: '八荒', chance: 500 }, { item: '半月', chance: 500 },
    { item: '海魂', chance: 500 }, { item: '凌风', chance: 500 },
    { item: '中型盔甲', chance: 250 },
  ],
  '月魔蜘蛛': [
    { item: '金币', chance: 5, count: 200 },
    { item: '金创药(中量)', chance: 15 }, { item: '魔法药(中量)', chance: 25 },
    { item: '太阳水', chance: 50 },
    { item: '半月弯刀', chance: 18000 }, { item: '地狱雷光', chance: 18000 },
    { item: '魔法盾', chance: 18000 }, { item: '困魔咒', chance: 18000 },
    // 技能书补全（原服务端1/6000档，爆率紧缩×3）
    { item: '野蛮冲撞', chance: 18000 }, { item: '圣言术', chance: 18000 },
    { item: '群体治愈术', chance: 18000 }, { item: '雷霆剑法', chance: 18000 },
    { item: '擒龙手', chance: 18000 }, { item: '寒冰掌', chance: 18000 },
    { item: '嗜血术', chance: 18000 }, { item: '气功波', chance: 18000 },
    { item: '净化术', chance: 18000 }, { item: '无极真气', chance: 18000 },
    { item: '死神手套', chance: 11200 }, { item: '蓝翡翠项链', chance: 11200 },
    { item: '金手镯', chance: 11200 }, { item: '道德戒指', chance: 11200 },
    { item: '魅力戒指', chance: 11200 }, { item: '放大镜', chance: 11200 },
    { item: '竹笛', chance: 11200 }, { item: '道士头盔', chance: 11200 },
    { item: '降妖除魔戒指', chance: 11200 }, { item: '金戒指', chance: 11200 },
    { item: '紫绸靴', chance: 11200 }, { item: '青铜腰带', chance: 11200 },
    { item: '金萤帽', chance: 11200 }, { item: '金铜头盔', chance: 11200 },
    { item: '青雷', chance: 11200 }, { item: '灵力项链', chance: 11200 },
    { item: '黑铁手镯', chance: 11200 }, { item: '火血匕', chance: 11200 },
    { item: '灵魂战衣', chance: 5600 },
    { item: '凝霜', chance: 11200 }, { item: '珊瑚戒指', chance: 11200 },
    { item: '骷髅头盔', chance: 11200 }, { item: '修罗', chance: 11200 },
    { item: '重盔甲', chance: 5600 }, { item: '魔法长袍', chance: 5600 },
    { item: '道士手镯', chance: 1400 }, { item: '降魔', chance: 1400 },
    { item: '斩马刀', chance: 1400 }, { item: '偃月', chance: 1400 },
    { item: '黑色水晶戒指', chance: 1400 }, { item: '蛇眼戒指', chance: 1400 },
    { item: '珍珠戒指', chance: 1400 }, { item: '破魂', chance: 1400 },
    { item: '白色虎齿项链', chance: 1400 }, { item: '白金项链', chance: 1400 },
    { item: '骷髅戒指', chance: 1400 }, { item: '鹿皮靴', chance: 1400 },
    { item: '铁腰带', chance: 1400 },
    { item: '八荒', chance: 500 }, { item: '半月', chance: 500 },
    { item: '中型盔甲', chance: 250 },
  ],
  '白野猪': [
    { item: '金币', chance: 1, count: 5000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效太阳水', chance: 2 },
    { item: '强效金创药', chance: 1 }, { item: '强效魔法药', chance: 1 },
    { item: '祝福油', chance: 100 },
    { item: '勇士头盔', chance: 320 }, { item: '紫晶石项链', chance: 320 },
    { item: '钢铁手套', chance: 320 }, { item: '破碎项链', chance: 320 },
    { item: '裁决之杖', chance: 2000 }, { item: '骨玉权杖', chance: 2000 },
    { item: '无极棍', chance: 2000 },
    { item: '幽灵项链', chance: 160 }, { item: '生命项链', chance: 160 },
    { item: '天珠项链', chance: 160 }, { item: '幽灵手套', chance: 160 },
    { item: '龙之戒指', chance: 160 }, { item: '红宝石戒指', chance: 160 },
    { item: '铂金戒指', chance: 160 }, { item: '避魂靴', chance: 160 },
    { item: '钢铁腰带', chance: 160 }, { item: '记忆项链', chance: 160 },
    { item: '战神盔甲', chance: 80 },
    { item: '恶魔长袍', chance: 80 },
    { item: '幽灵战衣', chance: 80 },
    { item: '炼狱', chance: 300 }, { item: '魔杖', chance: 300 },
    { item: '银蛇', chance: 300 }, { item: '井中月', chance: 300 },
    { item: '血饮', chance: 300 }, { item: '罗刹', chance: 300 },
    { item: '半月弯刀', chance: 250 }, { item: '地狱雷光', chance: 250 },
    { item: '魔法盾', chance: 250 }, { item: '烈火剑法', chance: 1800 },
    { item: '召唤神兽', chance: 1800 }, { item: '冰咆哮', chance: 1800 },
    // 技能书补全（原服务端1/85、1/600档，爆率紧缩×3；分身术/护身气幕/阴阳盾移至后期BOSS）
    { item: '困魔咒', chance: 250 }, { item: '野蛮冲撞', chance: 250 },
    { item: '圣言术', chance: 250 }, { item: '群体治愈术', chance: 250 },
    { item: '雷霆剑法', chance: 250 }, { item: '擒龙手', chance: 250 },
    { item: '寒冰掌', chance: 250 }, { item: '嗜血术', chance: 250 },
    { item: '气功波', chance: 250 }, { item: '净化术', chance: 250 },
    { item: '无极真气', chance: 250 },
    { item: '狮子吼', chance: 1800 }, { item: '双龙斩', chance: 1800 },
    { item: '龙影剑法', chance: 1800 },
    { item: '剑气爆', chance: 1800 }, { item: '灭天火', chance: 1800 },
    { item: '火龙气焰', chance: 1800 },
    { item: '天霜冰环', chance: 1800 }, { item: '深延术', chance: 1800 },
    { item: '召唤月灵', chance: 1800 }, { item: '诅咒术', chance: 1800 },
    { item: '血龙水', chance: 1800 },
    { item: '魔血戒指', chance: 2000 }, { item: '虹魔戒指', chance: 2000 },
    { item: '魔血手镯', chance: 2000 }, { item: '虹魔手镯', chance: 2000 },
    { item: '死神手套', chance: 400 }, { item: '蓝翡翠项链', chance: 400 },
    { item: '金手镯', chance: 400 }, { item: '道德戒指', chance: 400 },
    { item: '魅力戒指', chance: 400 }, { item: '放大镜', chance: 400 },
    { item: '竹笛', chance: 400 }, { item: '道士头盔', chance: 400 },
    { item: '降妖除魔戒指', chance: 400 }, { item: '金戒指', chance: 400 },
    { item: '紫绸靴', chance: 400 }, { item: '青铜腰带', chance: 400 },
    { item: '金萤帽', chance: 400 }, { item: '金铜头盔', chance: 400 },
    { item: '青雷', chance: 400 }, { item: '灵力项链', chance: 400 },
    { item: '黑铁手镯', chance: 400 }, { item: '火血匕', chance: 400 },
    { item: '钢铁头盔', chance: 400 }, { item: '记忆项链', chance: 400 },
    { item: '记忆头盔', chance: 400 }, { item: '灵晶甲胄', chance: 400 },
    { item: '思贝儿手镯', chance: 400 }, { item: '三眼手镯', chance: 400 },
    { item: '勇猛宝玉', chance: 400 }, { item: '魔性宝玉', chance: 400 },
    { item: '仙界宝玉', chance: 400 }, { item: '守护宝玉', chance: 400 },
    { item: '制魔宝玉', chance: 400 }, { item: '集中宝玉', chance: 400 },
    { item: '凝霜', chance: 400 }, { item: '珊瑚戒指', chance: 400 },
    { item: '骷髅头盔', chance: 400 }, { item: '修罗', chance: 400 },
    { item: '重盔甲', chance: 400 }, { item: '魔法长袍', chance: 400 },
    { item: '灵魂战衣', chance: 400 },
    { item: '道士手镯', chance: 3 }, { item: '黑檀手镯', chance: 3 },
    { item: '降魔', chance: 3 }, { item: '斩马刀', chance: 3 },
    { item: '偃月', chance: 3 }, { item: '生铁戒指', chance: 3 },
    { item: '黑色水晶戒指', chance: 3 }, { item: '蛇眼戒指', chance: 3 },
    { item: '珍珠戒指', chance: 3 }, { item: '破魂', chance: 3 },
    { item: '白色虎齿项链', chance: 3 }, { item: '白金项链', chance: 3 },
    { item: '骷髅戒指', chance: 3 }, { item: '鹿皮靴', chance: 3 },
    { item: '铁腰带', chance: 3 },
  ],
  '触龙神': [
    { item: '金币', chance: 1, count: 14000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效金创药', chance: 1 },
    { item: '强效魔法药', chance: 1 },
    { item: '祝福油', chance: 400 },
    { item: '勇士头盔', chance: 800 }, { item: '紫晶石项链', chance: 800 },
    { item: '钢铁手套', chance: 800 }, { item: '破碎项链', chance: 800 },
    { item: '裁决之杖', chance: 800 }, { item: '骨玉权杖', chance: 800 },
    { item: '无极棍', chance: 800 },
    { item: '幽灵项链', chance: 400 }, { item: '生命项链', chance: 400 },
    { item: '天珠项链', chance: 400 }, { item: '幽灵手套', chance: 400 },
    { item: '龙之戒指', chance: 400 }, { item: '红宝石戒指', chance: 400 },
    { item: '铂金戒指', chance: 400 }, { item: '避魂靴', chance: 400 },
    { item: '记忆项链', chance: 400 }, { item: '记忆头盔', chance: 400 },
    { item: '战神盔甲', chance: 400 }, { item: '恶魔长袍', chance: 400 },
    { item: '幽灵战衣', chance: 400 },
    { item: '炼狱', chance: 400 }, { item: '魔杖', chance: 400 },
    { item: '银蛇', chance: 400 }, { item: '井中月', chance: 400 },
    { item: '血饮', chance: 400 },
    { item: '半月弯刀', chance: 120 }, { item: '地狱雷光', chance: 120 },
    { item: '魔法盾', chance: 120 },
    { item: '烈火剑法', chance: 240 }, { item: '召唤神兽', chance: 240 },
    { item: '冰咆哮', chance: 240 },
    // 技能书补全（原服务端1/40、1/80档，爆率紧缩×3；分身术/护身气幕/阴阳盾移至后期BOSS）
    { item: '困魔咒', chance: 120 }, { item: '野蛮冲撞', chance: 120 },
    { item: '圣言术', chance: 120 }, { item: '群体治愈术', chance: 120 },
    { item: '雷霆剑法', chance: 120 }, { item: '擒龙手', chance: 120 },
    { item: '寒冰掌', chance: 120 }, { item: '嗜血术', chance: 120 },
    { item: '气功波', chance: 120 }, { item: '净化术', chance: 120 },
    { item: '无极真气', chance: 120 },
    { item: '狮子吼', chance: 240 }, { item: '双龙斩', chance: 240 },
    { item: '龙影剑法', chance: 240 },
    { item: '剑气爆', chance: 240 }, { item: '灭天火', chance: 240 },
    { item: '火龙气焰', chance: 240 },
    { item: '天霜冰环', chance: 240 }, { item: '深延术', chance: 240 },
    { item: '召唤月灵', chance: 240 }, { item: '诅咒术', chance: 240 },
    { item: '血龙水', chance: 240 },
    { item: '魔血戒指', chance: 1000 }, { item: '虹魔戒指', chance: 1000 },
    { item: '魔血手镯', chance: 1000 }, { item: '虹魔手镯', chance: 1000 },
    { item: '死神手套', chance: 80 }, { item: '蓝翡翠项链', chance: 80 },
    { item: '金手镯', chance: 80 }, { item: '道德戒指', chance: 80 },
    { item: '魅力戒指', chance: 80 }, { item: '放大镜', chance: 80 },
    { item: '竹笛', chance: 80 }, { item: '道士头盔', chance: 80 },
    { item: '降妖除魔戒指', chance: 80 }, { item: '金戒指', chance: 80 },
    { item: '紫绸靴', chance: 80 }, { item: '青铜腰带', chance: 80 },
    { item: '金萤帽', chance: 80 }, { item: '金铜头盔', chance: 80 },
    { item: '青雷', chance: 80 }, { item: '灵力项链', chance: 80 },
    { item: '黑铁手镯', chance: 80 }, { item: '火血匕', chance: 80 },
    { item: '钢铁头盔', chance: 80 }, { item: '记忆项链', chance: 80 },
    { item: '记忆头盔', chance: 80 }, { item: '灵晶甲胄', chance: 80 },
    { item: '思贝儿手镯', chance: 80 }, { item: '三眼手镯', chance: 80 },
    { item: '勇猛宝玉', chance: 80 }, { item: '魔性宝玉', chance: 80 },
    { item: '仙界宝玉', chance: 80 }, { item: '守护宝玉', chance: 80 },
    { item: '制魔宝玉', chance: 80 }, { item: '集中宝玉', chance: 80 },
    { item: '凝霜', chance: 80 }, { item: '珊瑚戒指', chance: 80 },
    { item: '骷髅头盔', chance: 80 }, { item: '修罗', chance: 80 },
    { item: '重盔甲', chance: 80 }, { item: '魔法长袍', chance: 80 },
    { item: '灵魂战衣', chance: 80 },
    { item: '道士手镯', chance: 40 }, { item: '黑檀手镯', chance: 40 },
    { item: '降魔', chance: 40 }, { item: '斩马刀', chance: 40 },
    { item: '偃月', chance: 40 }, { item: '生铁戒指', chance: 40 },
    { item: '黑色水晶戒指', chance: 40 }, { item: '蛇眼戒指', chance: 40 },
    { item: '珍珠戒指', chance: 40 }, { item: '破魂', chance: 40 },
    { item: '白色虎齿项链', chance: 40 }, { item: '白金项链', chance: 40 },
    { item: '骷髅戒指', chance: 40 }, { item: '鹿皮靴', chance: 40 },
    { item: '铁腰带', chance: 40 },
  ],
  '沃玛教主': [
    { item: '金币', chance: 1, count: 6000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效太阳水', chance: 1 },
    { item: '强效金创药', chance: 1 }, { item: '强效魔法药', chance: 1 },
    { item: '麻痹戒指', chance: 4000 }, { item: '护身戒指', chance: 4000 },
    { item: '传送戒指', chance: 4000 },
    { item: '复活戒指', chance: 4000 }, { item: '火焰戒指', chance: 4000 },
    { item: '超负载戒指', chance: 4000 }, { item: '防御戒指', chance: 4000 },
    { item: '祝福油', chance: 400 },
    { item: '勇士头盔', chance: 160 }, { item: '紫晶石项链', chance: 160 },
    { item: '钢铁手套', chance: 160 }, { item: '破碎项链', chance: 160 },
    { item: '幽灵项链', chance: 80 }, { item: '生命项链', chance: 80 },
    { item: '天珠项链', chance: 80 }, { item: '幽灵手套', chance: 80 },
    { item: '龙之戒指', chance: 80 }, { item: '红宝石戒指', chance: 80 },
    { item: '铂金戒指', chance: 80 }, { item: '避魂靴', chance: 80 },
    { item: '钢铁腰带', chance: 80 }, { item: '记忆项链', chance: 80 },
    { item: '记忆头盔', chance: 80 },
    { item: '法神头盔', chance: 800 }, { item: '法神项链', chance: 800 },
    { item: '法神手镯', chance: 800 }, { item: '法神戒指', chance: 800 },
    { item: '天尊头盔', chance: 800 }, { item: '天尊项链', chance: 800 },
    { item: '天尊手镯', chance: 800 }, { item: '天尊戒指', chance: 800 },
    { item: '战神盔甲', chance: 40 },
    { item: '幽灵战衣', chance: 40 },
    { item: '恶魔长袍', chance: 40 },
    { item: '炼狱', chance: 1600 }, { item: '魔杖', chance: 1600 },
    { item: '银蛇', chance: 1600 }, { item: '井中月', chance: 1600 },
    { item: '血饮', chance: 1600 }, { item: '罗刹', chance: 1600 },
    { item: '半月弯刀', chance: 250 }, { item: '地狱雷光', chance: 250 },
    { item: '烈火剑法', chance: 250 }, { item: '召唤神兽', chance: 250 },
    { item: '冰咆哮', chance: 250 }, { item: '魔法盾', chance: 250 },
    // 技能书补全（原服务端1/85档，爆率紧缩×3；分身术/护身气幕/阴阳盾移至后期BOSS）
    { item: '野蛮冲撞', chance: 250 }, { item: '圣言术', chance: 250 },
    { item: '群体治愈术', chance: 250 }, { item: '净化术', chance: 250 },
    { item: '擒龙手', chance: 250 },
    { item: '狮子吼', chance: 250 }, { item: '双龙斩', chance: 250 },
    { item: '龙影剑法', chance: 250 },
    { item: '剑气爆', chance: 250 }, { item: '灭天火', chance: 250 },
    { item: '火龙气焰', chance: 250 },
    { item: '天霜冰环', chance: 250 }, { item: '深延术', chance: 250 },
    { item: '诅咒术', chance: 250 }, { item: '血龙水', chance: 250 },
    { item: '狂风戒指', chance: 400 },
    { item: '记忆戒指', chance: 2000 },
    { item: '死神手套', chance: 80 }, { item: '蓝翡翠项链', chance: 80 },
    { item: '金手镯', chance: 80 }, { item: '珊瑚戒指', chance: 80 },
    { item: '道德戒指', chance: 80 }, { item: '魅力戒指', chance: 80 },
    { item: '放大镜', chance: 80 }, { item: '竹笛', chance: 80 },
    { item: '道士头盔', chance: 80 }, { item: '降妖除魔戒指', chance: 80 },
    { item: '金戒指', chance: 80 }, { item: '紫绸靴', chance: 80 },
    { item: '青铜腰带', chance: 80 }, { item: '金萤帽', chance: 80 },
    { item: '金铜头盔', chance: 80 }, { item: '青雷', chance: 80 },
    { item: '灵力项链', chance: 80 }, { item: '黑铁手镯', chance: 80 },
    { item: '火血匕', chance: 80 }, { item: '灵魂战衣', chance: 40 },
    { item: '魔法长袍', chance: 40 },
    { item: '道士手镯', chance: 2 }, { item: '黑檀手镯', chance: 2 },
    { item: '降魔', chance: 2 }, { item: '斩马刀', chance: 2 },
    { item: '偃月', chance: 2 }, { item: '生铁戒指', chance: 2 },
    { item: '骷髅戒指', chance: 2 }, { item: '鹿皮靴', chance: 2 },
    { item: '铁腰带', chance: 2 },
  ],
  '祖玛教主': [
    { item: '金币', chance: 1, count: 30000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效太阳水', chance: 1 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '麻痹戒指', chance: 4000 }, { item: '护身戒指', chance: 4000 },
    { item: '传送戒指', chance: 4000 }, { item: '复活戒指', chance: 4000 },
    { item: '火焰戒指', chance: 4000 }, { item: '防御戒指', chance: 4000 },
    { item: '祝福油', chance: 300 },
    { item: '祖玛裁决之杖', chance: 1000 }, { item: '祖玛骨玉权杖', chance: 1000 },
    { item: '祖玛无极棍', chance: 1000 },
    { item: '天衣无缝', chance: 1000 },
    { item: '英雄头盔', chance: 900 }, { item: '贤人帽', chance: 900 },
    { item: '通天冠', chance: 900 }, { item: '赤燐鞋', chance: 900 },
    { item: '金刚腰带', chance: 900 },
    { item: '屠龙', chance: 4000 }, { item: '嗜魂法杖', chance: 4000 },
    { item: '龙纹剑', chance: 4000 },
    { item: '绿色项链', chance: 800 }, { item: '恶魔铃铛', chance: 800 },
    { item: '灵魂项链', chance: 800 }, { item: '骑士手镯', chance: 800 },
    { item: '龙之手镯', chance: 800 }, { item: '心灵手镯', chance: 800 },
    { item: '阎罗手套', chance: 800 }, { item: '力量戒指', chance: 800 },
    { item: '泰坦戒指', chance: 800 }, { item: '紫碧螺', chance: 800 },
    { item: '黑铁头盔', chance: 800 }, { item: '龙行鞋', chance: 800 },
    { item: '黄金腰带', chance: 800 },
    { item: '鬼面铠甲', chance: 800 }, { item: '火龙魔衣', chance: 800 },
    { item: '玄天宝衣', chance: 800 },
    { item: '圣战头盔', chance: 1500 }, { item: '圣战项链', chance: 1500 },
    { item: '圣战手镯', chance: 1500 }, { item: '圣战戒指', chance: 1500 },
    { item: '圣战宝甲', chance: 2500 }, { item: '法神宝甲', chance: 2500 },
    { item: '天尊宝甲', chance: 2500 },
    { item: '怒斩', chance: 4000 }, { item: '龙牙', chance: 4000 },
    { item: '逍遥扇', chance: 4000 },
    { item: '裁决之杖', chance: 2000 }, { item: '骨玉权杖', chance: 2000 },
    { item: '无极棍', chance: 2000 },
    { item: '幽灵项链', chance: 40 }, { item: '生命项链', chance: 40 },
    { item: '天珠项链', chance: 40 }, { item: '幽灵手套', chance: 40 },
    { item: '龙之戒指', chance: 40 }, { item: '红宝石戒指', chance: 40 },
    { item: '铂金戒指', chance: 40 }, { item: '记忆项链', chance: 40 },
    { item: '战神盔甲', chance: 40 }, { item: '恶魔长袍', chance: 40 },
    { item: '炼狱', chance: 1000 }, { item: '魔杖', chance: 1000 },
    { item: '银蛇', chance: 1000 }, { item: '井中月', chance: 1000 },
    { item: '血饮', chance: 1000 },
    { item: '半月弯刀', chance: 500 }, { item: '烈火剑法', chance: 950 },
    { item: '召唤神兽', chance: 950 }, { item: '冰咆哮', chance: 950 },
    { item: '魔法盾', chance: 500 },
    // 技能书补全（原服务端1/160、1/320、1/1000档，爆率紧缩×3；分身术/护身气幕/阴阳盾移至后期BOSS）
    { item: '地狱雷光', chance: 500 }, { item: '困魔咒', chance: 500 },
    { item: '野蛮冲撞', chance: 500 }, { item: '圣言术', chance: 500 },
    { item: '群体治愈术', chance: 500 }, { item: '雷霆剑法', chance: 500 },
    { item: '擒龙手', chance: 500 }, { item: '寒冰掌', chance: 500 },
    { item: '嗜血术', chance: 500 }, { item: '气功波', chance: 500 },
    { item: '净化术', chance: 500 }, { item: '无极真气', chance: 500 },
    { item: '狮子吼', chance: 950 }, { item: '双龙斩', chance: 950 },
    { item: '龙影剑法', chance: 950 },
    { item: '剑气爆', chance: 950 }, { item: '灭天火', chance: 950 },
    { item: '火龙气焰', chance: 950 },
    { item: '天霜冰环', chance: 950 }, { item: '深延术', chance: 950 },
    { item: '诅咒术', chance: 950 }, { item: '血龙水', chance: 950 },
    { item: '冰焰术', chance: 3000 }, { item: '瘟疫', chance: 3000 },
    { item: '毒云', chance: 3000 },
    { item: '魔血戒指', chance: 500 }, { item: '魔血手镯', chance: 500 },
    { item: '虹魔戒指', chance: 500 }, { item: '虹魔手镯', chance: 500 },
    { item: '死神手套', chance: 60 }, { item: '蓝翡翠项链', chance: 60 },
    { item: '金手镯', chance: 60 }, { item: '道德戒指', chance: 60 },
    { item: '魅力戒指', chance: 60 }, { item: '放大镜', chance: 60 },
    { item: '竹笛', chance: 60 }, { item: '道士头盔', chance: 60 },
    { item: '降妖除魔戒指', chance: 60 }, { item: '金戒指', chance: 60 },
    { item: '紫绸靴', chance: 60 }, { item: '青铜腰带', chance: 60 },
    { item: '金萤帽', chance: 60 }, { item: '金铜头盔', chance: 60 },
    { item: '青雷', chance: 60 }, { item: '灵力项链', chance: 60 },
    { item: '黑铁手镯', chance: 60 }, { item: '火血匕', chance: 60 },
    { item: '钢铁头盔', chance: 60 }, { item: '记忆项链', chance: 60 },
    { item: '记忆头盔', chance: 60 }, { item: '灵晶甲胄', chance: 60 },
    { item: '思贝儿手镯', chance: 60 }, { item: '三眼手镯', chance: 60 },
    { item: '勇猛宝玉', chance: 60 }, { item: '魔性宝玉', chance: 60 },
    { item: '仙界宝玉', chance: 60 }, { item: '守护宝玉', chance: 60 },
    { item: '制魔宝玉', chance: 60 }, { item: '集中宝玉', chance: 60 },
    { item: '珊瑚戒指', chance: 60 }, { item: '骷髅头盔', chance: 60 },
    { item: '修罗', chance: 60 }, { item: '凝霜', chance: 60 },
    { item: '重盔甲', chance: 40 }, { item: '魔法长袍', chance: 40 },
    { item: '灵魂战衣', chance: 40 },
    { item: '道士手镯', chance: 20 }, { item: '黑檀手镯', chance: 20 },
    { item: '降魔', chance: 20 }, { item: '斩马刀', chance: 20 },
    { item: '偃月', chance: 20 }, { item: '生铁戒指', chance: 20 },
    { item: '黑色水晶戒指', chance: 20 }, { item: '蛇眼戒指', chance: 20 },
    { item: '珍珠戒指', chance: 20 }, { item: '破魂', chance: 20 },
    { item: '白色虎齿项链', chance: 20 }, { item: '白金项链', chance: 20 },
    { item: '骷髅戒指', chance: 20 }, { item: '鹿皮靴', chance: 20 },
    { item: '铁腰带', chance: 20 },
  ],
  '虹魔教主': [
    { item: '金币', chance: 1, count: 15000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效金创药', chance: 1 },
    { item: '强效魔法药', chance: 1 },
    { item: '麻痹戒指', chance: 4000 }, { item: '护身戒指', chance: 4000 },
    { item: '传送戒指', chance: 4000 }, { item: '复活戒指', chance: 4000 },
    { item: '火焰戒指', chance: 4000 }, { item: '防御戒指', chance: 4000 },
    { item: '天衣无缝', chance: 1000 },
    { item: '英雄头盔', chance: 900 }, { item: '贤人帽', chance: 900 },
    { item: '通天冠', chance: 900 }, { item: '赤燐鞋', chance: 900 },
    { item: '金刚腰带', chance: 900 },
    { item: '屠龙', chance: 4000 }, { item: '嗜魂法杖', chance: 4000 },
    { item: '龙纹剑', chance: 4000 },
    { item: '绿色项链', chance: 900 }, { item: '恶魔铃铛', chance: 900 },
    { item: '灵魂项链', chance: 900 }, { item: '骑士手镯', chance: 900 },
    { item: '力量戒指', chance: 900 }, { item: '泰坦戒指', chance: 900 },
    { item: '紫碧螺', chance: 900 }, { item: '黑铁头盔', chance: 900 },
    { item: '鬼面铠甲', chance: 900 }, { item: '火龙魔衣', chance: 900 },
    { item: '怒斩', chance: 2000 }, { item: '龙牙', chance: 2000 },
    { item: '逍遥扇', chance: 2000 },
    { item: '裁决之杖', chance: 600 }, { item: '骨玉权杖', chance: 600 },
    { item: '无极棍', chance: 600 },
    { item: '幽灵项链', chance: 600 }, { item: '生命项链', chance: 600 },
    { item: '天珠项链', chance: 600 }, { item: '龙之戒指', chance: 600 },
    { item: '红宝石戒指', chance: 600 }, { item: '铂金戒指', chance: 600 },
    { item: '炼狱', chance: 80 }, { item: '魔杖', chance: 80 },
    { item: '银蛇', chance: 80 }, { item: '井中月', chance: 80 },
    { item: '血饮', chance: 80 },
    { item: '半月弯刀', chance: 300 }, { item: '烈火剑法', chance: 900 },
    { item: '召唤神兽', chance: 900 }, { item: '冰咆哮', chance: 900 },
    // 技能书补全（原服务端1/100、1/300、1/1000档，爆率紧缩×3；分身术/护身气幕/阴阳盾移至后期BOSS）
    { item: '地狱雷光', chance: 300 }, { item: '困魔咒', chance: 300 },
    { item: '野蛮冲撞', chance: 300 }, { item: '魔法盾', chance: 300 },
    { item: '圣言术', chance: 300 }, { item: '群体治愈术', chance: 300 },
    { item: '雷霆剑法', chance: 300 }, { item: '擒龙手', chance: 300 },
    { item: '寒冰掌', chance: 300 }, { item: '嗜血术', chance: 300 },
    { item: '气功波', chance: 300 }, { item: '净化术', chance: 300 },
    { item: '无极真气', chance: 300 },
    { item: '狮子吼', chance: 900 }, { item: '双龙斩', chance: 900 },
    { item: '龙影剑法', chance: 900 },
    { item: '剑气爆', chance: 900 }, { item: '灭天火', chance: 900 },
    { item: '火龙气焰', chance: 900 },
    { item: '天霜冰环', chance: 900 }, { item: '深延术', chance: 900 },
    { item: '诅咒术', chance: 900 }, { item: '血龙水', chance: 900 },
    { item: '冰焰术', chance: 3000 }, { item: '瘟疫', chance: 3000 },
    { item: '毒云', chance: 3000 },
    { item: '天务', chance: 3000 }, { item: '逐日剑法', chance: 3000 },
    { item: '流星火雨', chance: 3000 },
    { item: '魔血戒指', chance: 1000 }, { item: '虹魔戒指', chance: 1000 },
    { item: '死神手套', chance: 100 }, { item: '蓝翡翠项链', chance: 100 },
    { item: '金手镯', chance: 100 }, { item: '道德戒指', chance: 100 },
    { item: '魅力戒指', chance: 100 }, { item: '放大镜', chance: 100 },
    { item: '竹笛', chance: 100 }, { item: '道士头盔', chance: 100 },
    { item: '降妖除魔戒指', chance: 100 }, { item: '金戒指', chance: 100 },
    { item: '紫绸靴', chance: 100 }, { item: '青铜腰带', chance: 100 },
    { item: '金萤帽', chance: 100 }, { item: '金铜头盔', chance: 100 },
    { item: '青雷', chance: 100 }, { item: '灵力项链', chance: 100 },
    { item: '黑铁手镯', chance: 100 }, { item: '火血匕', chance: 100 },
    { item: '重盔甲', chance: 100 }, { item: '灵魂战衣', chance: 100 },
    { item: '魔法长袍', chance: 100 },
    { item: '凝霜', chance: 100 }, { item: '珊瑚戒指', chance: 100 },
    { item: '骷髅头盔', chance: 100 }, { item: '修罗', chance: 100 },
    { item: '道士手镯', chance: 3 }, { item: '黑檀手镯', chance: 3 },
    { item: '降魔', chance: 3 }, { item: '斩马刀', chance: 3 },
    { item: '偃月', chance: 3 }, { item: '生铁戒指', chance: 3 },
    { item: '黑色水晶戒指', chance: 3 }, { item: '蛇眼戒指', chance: 3 },
    { item: '珍珠戒指', chance: 3 }, { item: '破魂', chance: 3 },
    { item: '白色虎齿项链', chance: 3 }, { item: '白金项链', chance: 3 },
    { item: '骷髅戒指', chance: 3 }, { item: '鹿皮靴', chance: 3 },
    { item: '铁腰带', chance: 3 },
  ],
  '赤月恶魔': [
    { item: '金币', chance: 1, count: 24000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效金创药', chance: 1 },
    { item: '强效魔法药', chance: 1 },
    { item: '麻痹戒指', chance: 6400 }, { item: '护身戒指', chance: 6400 },
    { item: '传送戒指', chance: 6400 }, { item: '复活戒指', chance: 6400 },
    { item: '火焰戒指', chance: 6400 }, { item: '防御戒指', chance: 6400 },
    { item: '绿色项链', chance: 800 }, { item: '恶魔铃铛', chance: 800 },
    { item: '灵魂项链', chance: 800 }, { item: '骑士手镯', chance: 800 },
    { item: '力量戒指', chance: 800 }, { item: '泰坦戒指', chance: 800 },
    { item: '紫碧螺', chance: 800 }, { item: '黑铁头盔', chance: 800 },
    { item: '鬼面铠甲', chance: 800 }, { item: '火龙魔衣', chance: 800 },
    { item: '玄天宝衣', chance: 800 },
    { item: '勇士头盔', chance: 80 }, { item: '紫晶石项链', chance: 80 },
    { item: '钢铁手套', chance: 80 }, { item: '破碎项链', chance: 80 },
    { item: '裁决之杖', chance: 1000 }, { item: '骨玉权杖', chance: 1000 },
    { item: '无极棍', chance: 1000 },
    // 赤月套装主产出（原版赤月恶魔即圣战/法神/天尊产地；定位介于祖玛与魔龙之间）
    { item: '圣战头盔', chance: 1000 }, { item: '圣战项链', chance: 1000 },
    { item: '圣战手镯', chance: 1000 }, { item: '圣战戒指', chance: 1000 },
    { item: '法神头盔', chance: 1000 }, { item: '法神项链', chance: 1000 },
    { item: '法神手镯', chance: 1000 }, { item: '法神戒指', chance: 1000 },
    { item: '天尊头盔', chance: 1000 }, { item: '天尊项链', chance: 1000 },
    { item: '天尊手镯', chance: 1000 }, { item: '天尊戒指', chance: 1000 },
    { item: '圣战宝甲', chance: 1500 }, { item: '法神宝甲', chance: 1500 },
    { item: '天尊宝甲', chance: 1500 },
    { item: '幽灵项链', chance: 40 }, { item: '生命项链', chance: 40 },
    { item: '天珠项链', chance: 40 }, { item: '龙之戒指', chance: 40 },
    { item: '红宝石戒指', chance: 40 }, { item: '铂金戒指', chance: 40 },
    { item: '炼狱', chance: 1000 }, { item: '魔杖', chance: 1000 },
    { item: '银蛇', chance: 1000 }, { item: '井中月', chance: 1000 },
    { item: '半月弯刀', chance: 250 }, { item: '烈火剑法', chance: 950 },
    { item: '召唤神兽', chance: 950 }, { item: '冰咆哮', chance: 950 },
    // 技能书补全（原服务端1/85、1/320档，爆率紧缩×3；分身术/护身气幕/阴阳盾移至后期BOSS）
    { item: '地狱雷光', chance: 250 }, { item: '困魔咒', chance: 250 },
    { item: '野蛮冲撞', chance: 250 }, { item: '魔法盾', chance: 250 },
    { item: '圣言术', chance: 250 }, { item: '群体治愈术', chance: 250 },
    { item: '雷霆剑法', chance: 250 }, { item: '擒龙手', chance: 250 },
    { item: '寒冰掌', chance: 250 }, { item: '嗜血术', chance: 250 },
    { item: '气功波', chance: 250 }, { item: '净化术', chance: 250 },
    { item: '无极真气', chance: 250 },
    { item: '狮子吼', chance: 950 }, { item: '双龙斩', chance: 950 },
    { item: '龙影剑法', chance: 950 },
    { item: '剑气爆', chance: 950 }, { item: '灭天火', chance: 950 },
    { item: '火龙气焰', chance: 950 },
    { item: '天霜冰环', chance: 950 }, { item: '深延术', chance: 950 },
    { item: '诅咒术', chance: 950 }, { item: '血龙水', chance: 950 },
    { item: '狂风戒指', chance: 640 },
    { item: '魔血戒指', chance: 300 }, { item: '虹魔戒指', chance: 300 },
    { item: '死神手套', chance: 60 }, { item: '蓝翡翠项链', chance: 60 },
    { item: '金手镯', chance: 60 }, { item: '道德戒指', chance: 60 },
    { item: '魅力戒指', chance: 60 }, { item: '放大镜', chance: 60 },
    { item: '竹笛', chance: 60 }, { item: '道士头盔', chance: 60 },
    { item: '降妖除魔戒指', chance: 60 }, { item: '金戒指', chance: 60 },
    { item: '紫绸靴', chance: 60 }, { item: '青铜腰带', chance: 60 },
    { item: '金萤帽', chance: 60 }, { item: '金铜头盔', chance: 60 },
    { item: '青雷', chance: 60 }, { item: '灵力项链', chance: 60 },
    { item: '黑铁手镯', chance: 60 }, { item: '火血匕', chance: 60 },
    { item: '重盔甲', chance: 60 }, { item: '灵魂战衣', chance: 60 },
    { item: '魔法长袍', chance: 60 },
    { item: '凝霜', chance: 60 }, { item: '珊瑚戒指', chance: 60 },
    { item: '骷髅头盔', chance: 60 }, { item: '修罗', chance: 60 },
    { item: '道士手镯', chance: 20 }, { item: '黑檀手镯', chance: 20 },
    { item: '降魔', chance: 20 }, { item: '斩马刀', chance: 20 },
    { item: '偃月', chance: 20 }, { item: '生铁戒指', chance: 20 },
    { item: '黑色水晶戒指', chance: 20 }, { item: '蛇眼戒指', chance: 20 },
    { item: '珍珠戒指', chance: 20 }, { item: '破魂', chance: 20 },
    { item: '白色虎齿项链', chance: 20 }, { item: '白金项链', chance: 20 },
    { item: '骷髅戒指', chance: 20 }, { item: '鹿皮靴', chance: 20 },
    { item: '铁腰带', chance: 20 },
  ],
  '牛魔王': [
    { item: '金币', chance: 1, count: 10000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效金创药', chance: 1 },
    { item: '强效魔法药', chance: 1 },
    { item: '麻痹戒指', chance: 4000 }, { item: '护身戒指', chance: 4000 },
    { item: '传送戒指', chance: 4000 }, { item: '复活戒指', chance: 4000 },
    { item: '火焰戒指', chance: 4000 }, { item: '防御戒指', chance: 4000 },
    { item: '天衣无缝', chance: 1000 },
    { item: '英雄头盔', chance: 900 }, { item: '贤人帽', chance: 900 },
    { item: '通天冠', chance: 900 }, { item: '赤燐鞋', chance: 900 },
    { item: '金刚腰带', chance: 900 },
    { item: '屠龙', chance: 3200 }, { item: '嗜魂法杖', chance: 3200 },
    { item: '龙纹剑', chance: 3200 },
    { item: '绿色项链', chance: 800 }, { item: '恶魔铃铛', chance: 800 },
    { item: '灵魂项链', chance: 800 }, { item: '骑士手镯', chance: 800 },
    { item: '力量戒指', chance: 800 }, { item: '泰坦戒指', chance: 800 },
    { item: '紫碧螺', chance: 800 }, { item: '黑铁头盔', chance: 800 },
    { item: '鬼面铠甲', chance: 800 }, { item: '火龙魔衣', chance: 800 },
    { item: '怒斩', chance: 4000 }, { item: '龙牙', chance: 4000 },
    { item: '逍遥扇', chance: 4000 },
    { item: '裁决之杖', chance: 1600 }, { item: '骨玉权杖', chance: 1600 },
    { item: '无极棍', chance: 1600 },
    { item: '幽灵项链', chance: 500 }, { item: '生命项链', chance: 500 },
    { item: '天珠项链', chance: 500 }, { item: '龙之戒指', chance: 500 },
    { item: '红宝石戒指', chance: 500 }, { item: '铂金戒指', chance: 500 },
    { item: '炼狱', chance: 800 }, { item: '魔杖', chance: 800 },
    { item: '银蛇', chance: 800 }, { item: '井中月', chance: 800 },
    { item: '半月弯刀', chance: 300 }, { item: '烈火剑法', chance: 600 },
    { item: '召唤神兽', chance: 600 }, { item: '冰咆哮', chance: 600 },
    // 技能书补全（原服务端1/100、1/200、1/1000档，爆率紧缩×3；三本高级书保留后期BOSS投放）
    { item: '地狱雷光', chance: 300 }, { item: '困魔咒', chance: 300 },
    { item: '野蛮冲撞', chance: 300 }, { item: '魔法盾', chance: 300 },
    { item: '圣言术', chance: 300 }, { item: '群体治愈术', chance: 300 },
    { item: '雷霆剑法', chance: 300 }, { item: '擒龙手', chance: 300 },
    { item: '寒冰掌', chance: 300 }, { item: '嗜血术', chance: 300 },
    { item: '气功波', chance: 300 }, { item: '净化术', chance: 300 },
    { item: '无极真气', chance: 300 },
    { item: '狮子吼', chance: 600 }, { item: '双龙斩', chance: 600 },
    { item: '龙影剑法', chance: 600 }, { item: '护身气幕', chance: 600 },
    { item: '剑气爆', chance: 600 }, { item: '灭天火', chance: 600 },
    { item: '分身术', chance: 600 }, { item: '火龙气焰', chance: 600 },
    { item: '天霜冰环', chance: 600 }, { item: '深延术', chance: 600 },
    { item: '诅咒术', chance: 600 }, { item: '血龙水', chance: 600 },
    { item: '阴阳盾', chance: 600 },
    { item: '冰焰术', chance: 3000 }, { item: '瘟疫', chance: 3000 },
    { item: '毒云', chance: 3000 },
    { item: '天务', chance: 3000 }, { item: '逐日剑法', chance: 3000 },
    { item: '流星火雨', chance: 3000 },
    { item: '魔血戒指', chance: 800 }, { item: '虹魔戒指', chance: 800 },
    { item: '死神手套', chance: 100 }, { item: '蓝翡翠项链', chance: 100 },
    { item: '金手镯', chance: 100 }, { item: '道德戒指', chance: 100 },
    { item: '魅力戒指', chance: 100 }, { item: '放大镜', chance: 100 },
    { item: '竹笛', chance: 100 }, { item: '道士头盔', chance: 100 },
    { item: '降妖除魔戒指', chance: 100 }, { item: '金戒指', chance: 100 },
    { item: '紫绸靴', chance: 100 }, { item: '青铜腰带', chance: 100 },
    { item: '金萤帽', chance: 100 }, { item: '金铜头盔', chance: 100 },
    { item: '青雷', chance: 100 }, { item: '灵力项链', chance: 100 },
    { item: '黑铁手镯', chance: 100 }, { item: '火血匕', chance: 100 },
    { item: '重盔甲', chance: 100 }, { item: '灵魂战衣', chance: 100 },
    { item: '魔法长袍', chance: 100 },
    { item: '凝霜', chance: 100 }, { item: '珊瑚戒指', chance: 100 },
    { item: '骷髅头盔', chance: 100 }, { item: '修罗', chance: 100 },
    { item: '道士手镯', chance: 3 }, { item: '黑檀手镯', chance: 3 },
    { item: '降魔', chance: 3 }, { item: '斩马刀', chance: 3 },
    { item: '偃月', chance: 3 }, { item: '生铁戒指', chance: 3 },
    { item: '黑色水晶戒指', chance: 3 }, { item: '蛇眼戒指', chance: 3 },
    { item: '珍珠戒指', chance: 3 }, { item: '破魂', chance: 3 },
    { item: '白色虎齿项链', chance: 3 }, { item: '白金项链', chance: 3 },
    { item: '骷髅戒指', chance: 3 }, { item: '鹿皮靴', chance: 3 },
    { item: '铁腰带', chance: 3 },
  ],
  '黄泉教主': [
    { item: '金币', chance: 1, count: 10000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效金创药', chance: 1 },
    { item: '强效魔法药', chance: 1 },
    { item: '麻痹戒指', chance: 4000 }, { item: '护身戒指', chance: 4000 },
    { item: '传送戒指', chance: 4000 }, { item: '复活戒指', chance: 4000 },
    { item: '火焰戒指', chance: 4000 }, { item: '防御戒指', chance: 4000 },
    { item: '天衣无缝', chance: 1000 },
    { item: '英雄头盔', chance: 900 }, { item: '贤人帽', chance: 900 },
    { item: '通天冠', chance: 900 }, { item: '赤燐鞋', chance: 900 },
    { item: '金刚腰带', chance: 900 },
    { item: '绿色项链', chance: 800 }, { item: '恶魔铃铛', chance: 800 },
    { item: '灵魂项链', chance: 800 }, { item: '骑士手镯', chance: 800 },
    { item: '力量戒指', chance: 800 }, { item: '泰坦戒指', chance: 800 },
    { item: '紫碧螺', chance: 800 }, { item: '黑铁头盔', chance: 800 },
    { item: '鬼面铠甲', chance: 800 }, { item: '火龙魔衣', chance: 800 },
    { item: '怒斩', chance: 4000 }, { item: '龙牙', chance: 4000 },
    { item: '逍遥扇', chance: 4000 },
    { item: '勇士头盔', chance: 80 }, { item: '紫晶石项链', chance: 80 },
    { item: '钢铁手套', chance: 80 }, { item: '破碎项链', chance: 80 },
    { item: '裁决之杖', chance: 2000 }, { item: '骨玉权杖', chance: 2000 },
    { item: '无极棍', chance: 2000 },
    { item: '幽灵项链', chance: 40 }, { item: '生命项链', chance: 40 },
    { item: '天珠项链', chance: 40 }, { item: '龙之戒指', chance: 40 },
    { item: '红宝石戒指', chance: 40 }, { item: '铂金戒指', chance: 40 },
    { item: '炼狱', chance: 1000 }, { item: '魔杖', chance: 1000 },
    { item: '银蛇', chance: 1000 }, { item: '井中月', chance: 1000 },
    { item: '半月弯刀', chance: 450 }, { item: '烈火剑法', chance: 900 },
    { item: '召唤神兽', chance: 900 }, { item: '冰咆哮', chance: 900 },
    // 技能书补全（原服务端1/150、1/300、1/1000档，爆率紧缩×3；三本高级书保留后期BOSS投放）
    { item: '地狱雷光', chance: 450 }, { item: '困魔咒', chance: 450 },
    { item: '野蛮冲撞', chance: 450 }, { item: '魔法盾', chance: 450 },
    { item: '圣言术', chance: 450 }, { item: '群体治愈术', chance: 450 },
    { item: '雷霆剑法', chance: 450 }, { item: '擒龙手', chance: 450 },
    { item: '寒冰掌', chance: 450 }, { item: '嗜血术', chance: 450 },
    { item: '气功波', chance: 450 }, { item: '净化术', chance: 450 },
    { item: '无极真气', chance: 450 },
    { item: '狮子吼', chance: 900 }, { item: '双龙斩', chance: 900 },
    { item: '龙影剑法', chance: 900 }, { item: '护身气幕', chance: 900 },
    { item: '剑气爆', chance: 900 }, { item: '灭天火', chance: 900 },
    { item: '分身术', chance: 900 }, { item: '火龙气焰', chance: 900 },
    { item: '天霜冰环', chance: 900 }, { item: '深延术', chance: 900 },
    { item: '诅咒术', chance: 900 }, { item: '血龙水', chance: 900 },
    { item: '阴阳盾', chance: 900 },
    { item: '冰焰术', chance: 3000 }, { item: '瘟疫', chance: 3000 },
    { item: '毒云', chance: 3000 },
    { item: '天务', chance: 3000 }, { item: '逐日剑法', chance: 3000 },
    { item: '流星火雨', chance: 3000 },
    { item: '狂风戒指', chance: 640 },
    { item: '魔血戒指', chance: 500 }, { item: '虹魔戒指', chance: 500 },
    { item: '死神手套', chance: 30 }, { item: '蓝翡翠项链', chance: 30 },
    { item: '金手镯', chance: 30 }, { item: '道德戒指', chance: 30 },
    { item: '魅力戒指', chance: 30 }, { item: '放大镜', chance: 30 },
    { item: '竹笛', chance: 30 }, { item: '道士头盔', chance: 30 },
    { item: '降妖除魔戒指', chance: 30 }, { item: '金戒指', chance: 30 },
    { item: '紫绸靴', chance: 30 }, { item: '青铜腰带', chance: 30 },
    { item: '金萤帽', chance: 30 }, { item: '金铜头盔', chance: 30 },
    { item: '青雷', chance: 30 }, { item: '灵力项链', chance: 30 },
    { item: '黑铁手镯', chance: 30 }, { item: '火血匕', chance: 30 },
    { item: '重盔甲', chance: 30 }, { item: '灵魂战衣', chance: 30 },
    { item: '魔法长袍', chance: 30 },
    { item: '凝霜', chance: 30 }, { item: '珊瑚戒指', chance: 30 },
    { item: '骷髅头盔', chance: 30 }, { item: '修罗', chance: 30 },
    { item: '道士手镯', chance: 2 }, { item: '黑檀手镯', chance: 2 },
    { item: '降魔', chance: 2 }, { item: '斩马刀', chance: 2 },
    { item: '偃月', chance: 2 }, { item: '生铁戒指', chance: 2 },
    { item: '黑色水晶戒指', chance: 2 }, { item: '蛇眼戒指', chance: 2 },
    { item: '珍珠戒指', chance: 2 }, { item: '破魂', chance: 2 },
    { item: '白色虎齿项链', chance: 2 }, { item: '白金项链', chance: 2 },
    { item: '骷髅戒指', chance: 2 }, { item: '鹿皮靴', chance: 2 },
    { item: '铁腰带', chance: 2 },
  ],
  '魔龙教主': [
    { item: '金币', chance: 1, count: 30000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 }, { item: '强效太阳水', chance: 2 },
    { item: '麻痹戒指', chance: 2000 }, { item: '护身戒指', chance: 2000 },
    { item: '传送戒指', chance: 2000 }, { item: '复活戒指', chance: 2000 },
    { item: '火焰戒指', chance: 2000 }, { item: '防御戒指', chance: 2000 },
    { item: '祝福油', chance: 20 },
    { item: '天衣无缝', chance: 300 },
    { item: '白驼臂铠', chance: 300 }, { item: '魂锁护腕', chance: 300 },
    { item: '太极护腕', chance: 300 },
    { item: '赤魔甲', chance: 300 }, { item: '绿魔甲', chance: 300 },
    { item: '青魔甲', chance: 300 },
    { item: '独孤九剑', chance: 1200 }, { item: '映邪天神', chance: 1200 },
    { item: '太极慧剑', chance: 1200 },
    { item: '英雄头盔', chance: 300 }, { item: '贤人帽', chance: 300 },
    { item: '通天冠', chance: 300 }, { item: '赤燐鞋', chance: 300 },
    { item: '金刚腰带', chance: 300 },
    { item: '水波项链', chance: 240 }, { item: '金刚铃项链', chance: 240 },
    { item: '镇魂项链', chance: 240 },
    { item: '屠龙', chance: 600 }, { item: '嗜魂法杖', chance: 600 },
    { item: '龙纹剑', chance: 600 },
    { item: '绿色项链', chance: 200 }, { item: '恶魔铃铛', chance: 200 },
    { item: '灵魂项链', chance: 200 }, { item: '骑士手镯', chance: 200 },
    { item: '力量戒指', chance: 200 }, { item: '泰坦戒指', chance: 200 },
    { item: '紫碧螺', chance: 200 }, { item: '黑铁头盔', chance: 200 },
    { item: '鬼面铠甲', chance: 200 }, { item: '火龙魔衣', chance: 200 },
    { item: '怒斩', chance: 240 }, { item: '龙牙', chance: 240 },
    { item: '逍遥扇', chance: 240 },
    { item: '裁决之杖', chance: 200 }, { item: '骨玉权杖', chance: 200 },
    { item: '无极棍', chance: 200 },
    { item: '幽灵项链', chance: 120 }, { item: '生命项链', chance: 120 },
    { item: '天珠项链', chance: 120 }, { item: '龙之戒指', chance: 120 },
    { item: '红宝石戒指', chance: 120 }, { item: '铂金戒指', chance: 120 },
    { item: '炼狱', chance: 160 }, { item: '魔杖', chance: 160 },
    { item: '银蛇', chance: 160 }, { item: '井中月', chance: 160 },
    // 装备补全（原服务端中低档段）
    { item: '龙之手镯', chance: 200 }, { item: '心灵手镯', chance: 200 },
    { item: '阎罗手套', chance: 200 }, { item: '龙行鞋', chance: 200 },
    { item: '黄金腰带', chance: 200 }, { item: '五玄项链', chance: 200 },
    { item: '五玄手镯', chance: 200 }, { item: '五玄戒指', chance: 200 },
    { item: '玄天宝衣', chance: 200 },
    { item: '幽灵手套', chance: 120 }, { item: '思贝儿手镯', chance: 120 },
    { item: '三眼手镯', chance: 120 }, { item: '避魂靴', chance: 120 },
    { item: '钢铁腰带', chance: 120 }, { item: '钢铁头盔', chance: 120 },
    { item: '记忆项链', chance: 120 }, { item: '记忆头盔', chance: 120 },
    { item: '战神盔甲', chance: 120 }, { item: '幽灵战衣', chance: 120 },
    { item: '恶魔长袍', chance: 120 }, { item: '灵晶甲胄', chance: 120 },
    { item: '勇猛宝玉', chance: 120 }, { item: '魔性宝玉', chance: 120 },
    { item: '仙界宝玉', chance: 120 }, { item: '守护宝玉', chance: 120 },
    { item: '制魔宝玉', chance: 120 }, { item: '集中宝玉', chance: 120 },
    { item: '魔血手镯', chance: 120 }, { item: '虹魔手镯', chance: 120 },
    { item: '金手镯', chance: 3 }, { item: '道德戒指', chance: 3 },
    { item: '魅力戒指', chance: 3 }, { item: '放大镜', chance: 3 },
    { item: '竹笛', chance: 3 }, { item: '道士头盔', chance: 3 },
    { item: '降妖除魔戒指', chance: 3 }, { item: '金戒指', chance: 3 },
    { item: '紫绸靴', chance: 3 }, { item: '青铜腰带', chance: 3 },
    { item: '金萤帽', chance: 3 }, { item: '金铜头盔', chance: 3 },
    { item: '青雷', chance: 3 }, { item: '灵力项链', chance: 3 },
    { item: '黑铁手镯', chance: 3 }, { item: '火血匕', chance: 3 },
    { item: '重盔甲', chance: 3 }, { item: '灵魂战衣', chance: 3 },
    { item: '魔法长袍', chance: 3 },
    { item: '天务', chance: 300 }, { item: '逐日剑法', chance: 300 },
    { item: '流星火雨', chance: 300 },
    { item: '冰焰术', chance: 300 }, { item: '瘟疫', chance: 300 },
    { item: '毒云', chance: 300 },
    // 三本高级书后期BOSS投放（爆率紧缩后）
    { item: '分身术', chance: 600 }, { item: '护身气幕', chance: 600 },
    { item: '阴阳盾', chance: 600 },
    { item: '魔血戒指', chance: 120 }, { item: '虹魔戒指', chance: 120 },
    { item: '死神手套', chance: 3 }, { item: '蓝翡翠项链', chance: 3 },
    { item: '凝霜', chance: 3 }, { item: '珊瑚戒指', chance: 3 },
    { item: '龙鳞', chance: 20 },
    { item: '圣战宝甲', chance: 800 }, { item: '法神宝甲', chance: 800 }, { item: '天尊宝甲', chance: 800 },
    { item: '圣战头盔', chance: 400 }, { item: '圣战项链', chance: 400 },
    { item: '圣战手镯', chance: 400 }, { item: '圣战戒指', chance: 400 },
    { item: '法神头盔', chance: 400 }, { item: '法神项链', chance: 400 },
    { item: '法神手镯', chance: 400 }, { item: '法神戒指', chance: 400 },
    { item: '天尊头盔', chance: 400 }, { item: '天尊项链', chance: 400 },
    { item: '天尊手镯', chance: 400 }, { item: '天尊戒指', chance: 400 },
  ],
  '火龙教主': [
    { item: '金币', chance: 1, count: 30000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 }, { item: '万年雪霜', chance: 1 },
    { item: '麻痹戒指', chance: 2000 }, { item: '护身戒指', chance: 2000 },
    { item: '传送戒指', chance: 2000 }, { item: '复活戒指', chance: 2000 },
    { item: '火焰戒指', chance: 2000 }, { item: '防御戒指', chance: 2000 },
    { item: '祝福油', chance: 20 },
    { item: '天衣无缝', chance: 300 },
    { item: '白驼臂铠', chance: 300 }, { item: '魂锁护腕', chance: 300 },
    { item: '太极护腕', chance: 300 },
    { item: '赤魔甲', chance: 300 }, { item: '绿魔甲', chance: 300 },
    { item: '青魔甲', chance: 300 },
    { item: '独孤九剑', chance: 1200 }, { item: '映邪天神', chance: 1200 },
    { item: '太极慧剑', chance: 1200 },
    { item: '英雄头盔', chance: 300 }, { item: '贤人帽', chance: 300 },
    { item: '通天冠', chance: 300 }, { item: '赤燐鞋', chance: 300 },
    { item: '金刚腰带', chance: 300 },
    { item: '水波项链', chance: 240 }, { item: '金刚铃项链', chance: 240 },
    { item: '镇魂项链', chance: 240 },
    { item: '屠龙', chance: 600 }, { item: '嗜魂法杖', chance: 600 },
    { item: '龙纹剑', chance: 600 },
    { item: '绿色项链', chance: 200 }, { item: '恶魔铃铛', chance: 200 },
    { item: '灵魂项链', chance: 200 }, { item: '骑士手镯', chance: 200 },
    { item: '力量戒指', chance: 200 }, { item: '泰坦戒指', chance: 200 },
    { item: '紫碧螺', chance: 200 }, { item: '黑铁头盔', chance: 200 },
    { item: '鬼面铠甲', chance: 200 }, { item: '火龙魔衣', chance: 200 },
    { item: '怒斩', chance: 240 }, { item: '龙牙', chance: 240 },
    { item: '逍遥扇', chance: 240 },
    { item: '裁决之杖', chance: 200 }, { item: '骨玉权杖', chance: 200 },
    { item: '无极棍', chance: 200 },
    { item: '幽灵项链', chance: 120 }, { item: '生命项链', chance: 120 },
    { item: '天珠项链', chance: 120 }, { item: '龙之戒指', chance: 120 },
    { item: '红宝石戒指', chance: 120 }, { item: '铂金戒指', chance: 120 },
    { item: '炼狱', chance: 160 }, { item: '魔杖', chance: 160 },
    { item: '银蛇', chance: 160 }, { item: '井中月', chance: 160 },
    // 装备补全（原服务端中低档段，参照魔龙教主）
    { item: '龙之手镯', chance: 200 }, { item: '心灵手镯', chance: 200 },
    { item: '阎罗手套', chance: 200 }, { item: '龙行鞋', chance: 200 },
    { item: '黄金腰带', chance: 200 }, { item: '五玄项链', chance: 200 },
    { item: '五玄手镯', chance: 200 }, { item: '五玄戒指', chance: 200 },
    { item: '玄天宝衣', chance: 200 },
    { item: '幽灵手套', chance: 120 }, { item: '思贝儿手镯', chance: 120 },
    { item: '三眼手镯', chance: 120 }, { item: '避魂靴', chance: 120 },
    { item: '钢铁腰带', chance: 120 }, { item: '钢铁头盔', chance: 120 },
    { item: '记忆项链', chance: 120 }, { item: '记忆头盔', chance: 120 },
    { item: '战神盔甲', chance: 120 }, { item: '幽灵战衣', chance: 120 },
    { item: '恶魔长袍', chance: 120 }, { item: '灵晶甲胄', chance: 120 },
    { item: '勇猛宝玉', chance: 120 }, { item: '魔性宝玉', chance: 120 },
    { item: '仙界宝玉', chance: 120 }, { item: '守护宝玉', chance: 120 },
    { item: '制魔宝玉', chance: 120 }, { item: '集中宝玉', chance: 120 },
    { item: '魔血手镯', chance: 120 }, { item: '虹魔手镯', chance: 120 },
    { item: '金手镯', chance: 3 }, { item: '道德戒指', chance: 3 },
    { item: '魅力戒指', chance: 3 }, { item: '放大镜', chance: 3 },
    { item: '竹笛', chance: 3 }, { item: '道士头盔', chance: 3 },
    { item: '降妖除魔戒指', chance: 3 }, { item: '金戒指', chance: 3 },
    { item: '紫绸靴', chance: 3 }, { item: '青铜腰带', chance: 3 },
    { item: '金萤帽', chance: 3 }, { item: '金铜头盔', chance: 3 },
    { item: '青雷', chance: 3 }, { item: '灵力项链', chance: 3 },
    { item: '黑铁手镯', chance: 3 }, { item: '火血匕', chance: 3 },
    { item: '重盔甲', chance: 3 }, { item: '灵魂战衣', chance: 3 },
    { item: '魔法长袍', chance: 3 },
    { item: '天务', chance: 300 }, { item: '逐日剑法', chance: 300 },
    { item: '流星火雨', chance: 300 },
    { item: '冰焰术', chance: 300 }, { item: '瘟疫', chance: 300 },
    { item: '毒云', chance: 300 },
    // 三本高级书后期BOSS投放（爆率紧缩后）
    { item: '分身术', chance: 600 }, { item: '护身气幕', chance: 600 },
    { item: '阴阳盾', chance: 600 },
    { item: '狂风戒指', chance: 160 },
    { item: '魔血戒指', chance: 120 }, { item: '虹魔戒指', chance: 120 },
    { item: '死神手套', chance: 3 }, { item: '蓝翡翠项链', chance: 3 },
    { item: '凝霜', chance: 3 }, { item: '珊瑚戒指', chance: 3 },
    { item: '圣战宝甲', chance: 800 }, { item: '法神宝甲', chance: 800 }, { item: '天尊宝甲', chance: 800 },
    { item: '圣战头盔', chance: 400 }, { item: '圣战项链', chance: 400 },
    { item: '圣战手镯', chance: 400 }, { item: '圣战戒指', chance: 400 },
    { item: '法神头盔', chance: 400 }, { item: '法神项链', chance: 400 },
    { item: '法神手镯', chance: 400 }, { item: '法神戒指', chance: 400 },
    { item: '天尊头盔', chance: 400 }, { item: '天尊项链', chance: 400 },
    { item: '天尊手镯', chance: 400 }, { item: '天尊戒指', chance: 400 },
  ],
  '南蛮野兽王': [
    { item: '金币', chance: 1, count: 20000 },
    { item: '强效太阳水', chance: 1 }, { item: '强效金创药', chance: 1 },
    { item: '强效魔法药', chance: 1 },
    { item: '麻痹戒指', chance: 3000 }, { item: '护身戒指', chance: 3000 },
    { item: '传送戒指', chance: 3000 }, { item: '复活戒指', chance: 3000 },
    { item: '火焰戒指', chance: 3000 }, { item: '防御戒指', chance: 3000 },
    { item: '天衣无缝', chance: 400 },
    { item: '英雄头盔', chance: 400 }, { item: '贤人帽', chance: 400 },
    { item: '通天冠', chance: 400 }, { item: '赤燐鞋', chance: 400 },
    { item: '金刚腰带', chance: 400 },
    { item: '屠龙', chance: 800 }, { item: '嗜魂法杖', chance: 800 },
    { item: '龙纹剑', chance: 800 },
    { item: '绿色项链', chance: 300 }, { item: '恶魔铃铛', chance: 300 },
    { item: '灵魂项链', chance: 300 }, { item: '骑士手镯', chance: 300 },
    { item: '力量戒指', chance: 300 }, { item: '泰坦戒指', chance: 300 },
    { item: '紫碧螺', chance: 300 }, { item: '黑铁头盔', chance: 300 },
    { item: '鬼面铠甲', chance: 300 }, { item: '火龙魔衣', chance: 300 },
    { item: '怒斩', chance: 1000 }, { item: '龙牙', chance: 1000 },
    { item: '逍遥扇', chance: 1000 },
    { item: '裁决之杖', chance: 400 }, { item: '骨玉权杖', chance: 400 },
    { item: '无极棍', chance: 400 },
    { item: '天务', chance: 600 }, { item: '逐日剑法', chance: 600 },
    { item: '流星火雨', chance: 600 },
    { item: '冰焰术', chance: 300 }, { item: '瘟疫', chance: 300 },
    { item: '毒云', chance: 300 },
    // 三本高级书后期BOSS投放（爆率紧缩后）
    { item: '分身术', chance: 600 }, { item: '护身气幕', chance: 600 },
    { item: '阴阳盾', chance: 600 },
    { item: '死神手套', chance: 10 }, { item: '蓝翡翠项链', chance: 10 },
    { item: '凝霜', chance: 10 }, { item: '珊瑚戒指', chance: 10 },
    // 装备补全（原服务端中低档段）
    { item: '祝福油', chance: 2 },
    { item: '独孤九剑', chance: 1200 }, { item: '映邪天神', chance: 1200 },
    { item: '太极慧剑', chance: 1200 },
    { item: '幽灵项链', chance: 40 }, { item: '生命项链', chance: 40 },
    { item: '天珠项链', chance: 40 }, { item: '幽灵手套', chance: 40 },
    { item: '思贝儿手镯', chance: 40 }, { item: '三眼手镯', chance: 40 },
    { item: '龙之戒指', chance: 40 }, { item: '红宝石戒指', chance: 40 },
    { item: '铂金戒指', chance: 40 }, { item: '避魂靴', chance: 40 },
    { item: '钢铁腰带', chance: 40 }, { item: '钢铁头盔', chance: 40 },
    { item: '记忆项链', chance: 40 }, { item: '记忆头盔', chance: 40 },
    { item: '战神盔甲', chance: 40 }, { item: '幽灵战衣', chance: 40 },
    { item: '恶魔长袍', chance: 40 }, { item: '灵晶甲胄', chance: 40 },
    { item: '龙之手镯', chance: 80 }, { item: '心灵手镯', chance: 80 },
    { item: '阎罗手套', chance: 80 }, { item: '龙行鞋', chance: 80 },
    { item: '黄金腰带', chance: 80 }, { item: '五玄项链', chance: 80 },
    { item: '五玄手镯', chance: 80 }, { item: '五玄戒指', chance: 80 },
    { item: '玄天宝衣', chance: 80 },
    { item: '炼狱', chance: 40 }, { item: '魔杖', chance: 40 },
    { item: '银蛇', chance: 40 }, { item: '井中月', chance: 40 },
    { item: '血饮', chance: 40 }, { item: '罗刹', chance: 40 },
    { item: '金手镯', chance: 5 }, { item: '道德戒指', chance: 5 },
    { item: '魅力戒指', chance: 5 }, { item: '放大镜', chance: 5 },
    { item: '竹笛', chance: 5 }, { item: '道士头盔', chance: 5 },
    { item: '降妖除魔戒指', chance: 5 }, { item: '金戒指', chance: 5 },
    { item: '紫绸靴', chance: 5 }, { item: '青铜腰带', chance: 5 },
    { item: '金萤帽', chance: 5 }, { item: '金铜头盔', chance: 5 },
    { item: '青雷', chance: 5 }, { item: '灵力项链', chance: 5 },
    { item: '黑铁手镯', chance: 5 }, { item: '火血匕', chance: 5 },
    { item: '重盔甲', chance: 5 }, { item: '灵魂战衣', chance: 5 },
    { item: '魔法长袍', chance: 5 },
  ],
  // === 通天塔Boss专属掉落 (13-18层: 中高级) ===
  '雷炎蛛王': [
    { item: '金币', chance: 1, count: 15000 },
    { item: '强效金创药', chance: 2 }, { item: '强效魔法药', chance: 2 },
    { item: '强效太阳水', chance: 3 },
    { item: '麻痹戒指', chance: 3000 }, { item: '护身戒指', chance: 3000 },
    { item: '传送戒指', chance: 3000 }, { item: '复活戒指', chance: 3000 },
    { item: '裁决之杖', chance: 400 }, { item: '骨玉权杖', chance: 400 },
    { item: '无极棍', chance: 400 },
    { item: '屠龙', chance: 1200 }, { item: '嗜魂法杖', chance: 1200 },
    { item: '龙纹剑', chance: 1200 },
    { item: '战神盔甲', chance: 500 }, { item: '恶魔长袍', chance: 500 },
    { item: '幽灵战衣', chance: 500 },
    { item: '英雄头盔', chance: 600 }, { item: '贤人帽', chance: 600 },
    { item: '通天冠', chance: 600 },
    { item: '绿色项链', chance: 500 }, { item: '恶魔铃铛', chance: 500 },
    { item: '灵魂项链', chance: 500 },
    { item: '力量戒指', chance: 500 }, { item: '泰坦戒指', chance: 500 },
    { item: '紫碧螺', chance: 500 },
    { item: '骑士手镯', chance: 400 }, { item: '龙之手镯', chance: 400 },
    { item: '心灵手镯', chance: 400 },
    { item: '雷霆剑法', chance: 900 }, { item: '冰咆哮', chance: 900 },
    { item: '召唤神兽', chance: 900 },
  ],
  '骷髅统领': [
    { item: '金币', chance: 1, count: 16000 },
    { item: '强效金创药', chance: 2 }, { item: '强效魔法药', chance: 2 },
    { item: '强效太阳水', chance: 3 },
    { item: '麻痹戒指', chance: 3000 }, { item: '护身戒指', chance: 3000 },
    { item: '传送戒指', chance: 3000 }, { item: '复活戒指', chance: 3000 },
    { item: '裁决之杖', chance: 400 }, { item: '骨玉权杖', chance: 400 },
    { item: '无极棍', chance: 400 },
    { item: '屠龙', chance: 1200 }, { item: '嗜魂法杖', chance: 1200 },
    { item: '龙纹剑', chance: 1200 },
    { item: '战神盔甲', chance: 500 }, { item: '恶魔长袍', chance: 500 },
    { item: '幽灵战衣', chance: 500 },
    { item: '英雄头盔', chance: 600 }, { item: '贤人帽', chance: 600 },
    { item: '通天冠', chance: 600 },
    { item: '绿色项链', chance: 500 }, { item: '恶魔铃铛', chance: 500 },
    { item: '灵魂项链', chance: 500 },
    { item: '力量戒指', chance: 500 }, { item: '泰坦戒指', chance: 500 },
    { item: '紫碧螺', chance: 500 },
    { item: '骑士手镯', chance: 400 }, { item: '龙之手镯', chance: 400 },
    { item: '心灵手镯', chance: 400 },
    { item: '雷霆剑法', chance: 900 }, { item: '冰咆哮', chance: 900 },
    { item: '召唤神兽', chance: 900 },
  ],
  '雪域魔王': [
    { item: '金币', chance: 1, count: 18000 },
    { item: '强效金创药', chance: 2 }, { item: '强效魔法药', chance: 2 },
    { item: '强效太阳水', chance: 2 },
    { item: '麻痹戒指', chance: 2500 }, { item: '护身戒指', chance: 2500 },
    { item: '传送戒指', chance: 2500 }, { item: '复活戒指', chance: 2500 },
    { item: '火焰戒指', chance: 2500 }, { item: '防御戒指', chance: 2500 },
    { item: '裁决之杖', chance: 350 }, { item: '骨玉权杖', chance: 350 },
    { item: '无极棍', chance: 350 },
    { item: '屠龙', chance: 1000 }, { item: '嗜魂法杖', chance: 1000 },
    { item: '龙纹剑', chance: 1000 },
    { item: '怒斩', chance: 2000 }, { item: '龙牙', chance: 2000 },
    { item: '逍遥扇', chance: 2000 },
    { item: '天衣无缝', chance: 600 }, { item: '赤魔甲', chance: 600 },
    { item: '绿魔甲', chance: 600 },
    { item: '英雄头盔', chance: 500 }, { item: '贤人帽', chance: 500 },
    { item: '通天冠', chance: 500 },
    { item: '绿色项链', chance: 400 }, { item: '恶魔铃铛', chance: 400 },
    { item: '灵魂项链', chance: 400 },
    { item: '力量戒指', chance: 400 }, { item: '泰坦戒指', chance: 400 },
    { item: '紫碧螺', chance: 400 }, { item: '黑铁头盔', chance: 400 },
    { item: '天务', chance: 750 }, { item: '逐日剑法', chance: 750 },
    { item: '流星火雨', chance: 750 }, { item: '召唤月灵', chance: 750 },
  ],
  '火龙': [
    { item: '金币', chance: 1, count: 20000 },
    { item: '金创药(特量)', chance: 2 }, { item: '魔法药(特量)', chance: 2 },
    { item: '强效太阳水', chance: 2 },
    { item: '麻痹戒指', chance: 2500 }, { item: '护身戒指', chance: 2500 },
    { item: '传送戒指', chance: 2500 }, { item: '复活戒指', chance: 2500 },
    { item: '火焰戒指', chance: 2500 }, { item: '防御戒指', chance: 2500 },
    { item: '裁决之杖', chance: 300 }, { item: '骨玉权杖', chance: 300 },
    { item: '无极棍', chance: 300 },
    { item: '屠龙', chance: 800 }, { item: '嗜魂法杖', chance: 800 },
    { item: '龙纹剑', chance: 800 },
    { item: '怒斩', chance: 1500 }, { item: '龙牙', chance: 1500 },
    { item: '逍遥扇', chance: 1500 },
    { item: '天衣无缝', chance: 500 }, { item: '赤魔甲', chance: 500 },
    { item: '绿魔甲', chance: 500 }, { item: '鬼面铠甲', chance: 500 },
    { item: '火龙魔衣', chance: 500 },
    { item: '英雄头盔', chance: 400 }, { item: '贤人帽', chance: 400 },
    { item: '通天冠', chance: 400 }, { item: '黑铁头盔', chance: 400 },
    { item: '绿色项链', chance: 350 }, { item: '恶魔铃铛', chance: 350 },
    { item: '灵魂项链', chance: 350 },
    { item: '力量戒指', chance: 350 }, { item: '泰坦戒指', chance: 350 },
    { item: '紫碧螺', chance: 350 },
    { item: '骑士手镯', chance: 300 }, { item: '阎罗手套', chance: 300 },
    { item: '天务', chance: 600 }, { item: '逐日剑法', chance: 600 },
    { item: '流星火雨', chance: 600 }, { item: '召唤月灵', chance: 600 },
    { item: '魔血戒指', chance: 300 }, { item: '虹魔戒指', chance: 300 },
  ],
  // === 通天塔Boss专属掉落 (19-25层: 顶级) ===
  '泯灭脑魔': [
    { item: '金币', chance: 1, count: 25000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 2000 }, { item: '护身戒指', chance: 2000 },
    { item: '传送戒指', chance: 2000 }, { item: '复活戒指', chance: 2000 },
    { item: '火焰戒指', chance: 2000 }, { item: '防御戒指', chance: 2000 },
    { item: '超负载戒指', chance: 2000 }, { item: '记忆戒指', chance: 2000 },
    { item: '屠龙', chance: 600 }, { item: '嗜魂法杖', chance: 600 },
    { item: '龙纹剑', chance: 600 },
    { item: '怒斩', chance: 1000 }, { item: '龙牙', chance: 1000 },
    { item: '逍遥扇', chance: 1000 },
    { item: '天衣无缝', chance: 400 }, { item: '赤魔甲', chance: 400 },
    { item: '绿魔甲', chance: 400 }, { item: '鬼面铠甲', chance: 400 },
    { item: '火龙魔衣', chance: 400 }, { item: '玄天宝衣', chance: 400 },
    { item: '绿色项链', chance: 300 }, { item: '恶魔铃铛', chance: 300 },
    { item: '灵魂项链', chance: 300 }, { item: '五玄项链', chance: 300 },
    { item: '力量戒指', chance: 300 }, { item: '泰坦戒指', chance: 300 },
    { item: '紫碧螺', chance: 300 }, { item: '五玄戒指', chance: 300 },
    { item: '黑铁头盔', chance: 300 }, { item: '骑士手镯', chance: 300 },
    { item: '阎罗手套', chance: 300 }, { item: '五玄手镯', chance: 300 },
    { item: '天务', chance: 450 }, { item: '逐日剑法', chance: 450 },
    { item: '流星火雨', chance: 450 }, { item: '召唤月灵', chance: 450 },
    { item: '魔血戒指', chance: 200 }, { item: '虹魔戒指', chance: 200 },
  ],
  '不屈英灵': [
    { item: '金币', chance: 1, count: 26000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 2000 }, { item: '护身戒指', chance: 2000 },
    { item: '传送戒指', chance: 2000 }, { item: '复活戒指', chance: 2000 },
    { item: '火焰戒指', chance: 2000 }, { item: '防御戒指', chance: 2000 },
    { item: '超负载戒指', chance: 2000 }, { item: '记忆戒指', chance: 2000 },
    { item: '屠龙', chance: 600 }, { item: '嗜魂法杖', chance: 600 },
    { item: '龙纹剑', chance: 600 },
    { item: '怒斩', chance: 1000 }, { item: '龙牙', chance: 1000 },
    { item: '逍遥扇', chance: 1000 },
    { item: '天衣无缝', chance: 400 }, { item: '赤魔甲', chance: 400 },
    { item: '绿魔甲', chance: 400 }, { item: '鬼面铠甲', chance: 400 },
    { item: '火龙魔衣', chance: 400 }, { item: '玄天宝衣', chance: 400 },
    { item: '绿色项链', chance: 300 }, { item: '恶魔铃铛', chance: 300 },
    { item: '灵魂项链', chance: 300 }, { item: '五玄项链', chance: 300 },
    { item: '力量戒指', chance: 300 }, { item: '泰坦戒指', chance: 300 },
    { item: '紫碧螺', chance: 300 }, { item: '五玄戒指', chance: 300 },
    { item: '黑铁头盔', chance: 300 }, { item: '骑士手镯', chance: 300 },
    { item: '阎罗手套', chance: 300 }, { item: '五玄手镯', chance: 300 },
    { item: '天务', chance: 450 }, { item: '逐日剑法', chance: 450 },
    { item: '流星火雨', chance: 450 }, { item: '召唤月灵', chance: 450 },
    { item: '魔血戒指', chance: 200 }, { item: '虹魔戒指', chance: 200 },
  ],
  '幽灵教主': [
    { item: '金币', chance: 1, count: 28000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 2000 }, { item: '护身戒指', chance: 2000 },
    { item: '传送戒指', chance: 2000 }, { item: '复活戒指', chance: 2000 },
    { item: '火焰戒指', chance: 2000 }, { item: '防御戒指', chance: 2000 },
    { item: '超负载戒指', chance: 2000 }, { item: '记忆戒指', chance: 2000 },
    { item: '祝福油', chance: 20 },
    { item: '屠龙', chance: 500 }, { item: '嗜魂法杖', chance: 500 },
    { item: '龙纹剑', chance: 500 },
    { item: '怒斩', chance: 800 }, { item: '龙牙', chance: 800 },
    { item: '逍遥扇', chance: 800 },
    { item: '天衣无缝', chance: 350 }, { item: '赤魔甲', chance: 350 },
    { item: '绿魔甲', chance: 350 }, { item: '鬼面铠甲', chance: 350 },
    { item: '火龙魔衣', chance: 350 }, { item: '玄天宝衣', chance: 350 },
    { item: '绿色项链', chance: 250 }, { item: '恶魔铃铛', chance: 250 },
    { item: '灵魂项链', chance: 250 }, { item: '五玄项链', chance: 250 },
    { item: '力量戒指', chance: 250 }, { item: '泰坦戒指', chance: 250 },
    { item: '紫碧螺', chance: 250 }, { item: '五玄戒指', chance: 250 },
    { item: '黑铁头盔', chance: 250 }, { item: '骑士手镯', chance: 250 },
    { item: '阎罗手套', chance: 250 }, { item: '五玄手镯', chance: 250 },
    { item: '天务', chance: 360 }, { item: '逐日剑法', chance: 360 },
    { item: '流星火雨', chance: 360 }, { item: '召唤月灵', chance: 360 },
    // 三本高级书后期BOSS投放（爆率紧缩后）
    { item: '分身术', chance: 450 }, { item: '护身气幕', chance: 450 },
    { item: '阴阳盾', chance: 450 },
    { item: '魔血戒指', chance: 150 }, { item: '虹魔戒指', chance: 150 },
    { item: '圣战宝甲', chance: 800 }, { item: '法神宝甲', chance: 800 }, { item: '天尊宝甲', chance: 800 },
    { item: '圣战头盔', chance: 400 }, { item: '圣战项链', chance: 400 },
    { item: '圣战手镯', chance: 400 }, { item: '圣战戒指', chance: 400 },
    { item: '法神头盔', chance: 400 }, { item: '法神项链', chance: 400 },
    { item: '法神手镯', chance: 400 }, { item: '法神戒指', chance: 400 },
    { item: '天尊头盔', chance: 400 }, { item: '天尊项链', chance: 400 },
    { item: '天尊手镯', chance: 400 }, { item: '天尊戒指', chance: 400 },
  ],
  '太阴玉兔': [
    { item: '金币', chance: 1, count: 30000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 1800 }, { item: '护身戒指', chance: 1800 },
    { item: '传送戒指', chance: 1800 }, { item: '复活戒指', chance: 1800 },
    { item: '火焰戒指', chance: 1800 }, { item: '防御戒指', chance: 1800 },
    { item: '超负载戒指', chance: 1800 }, { item: '记忆戒指', chance: 1800 },
    { item: '屠龙', chance: 500 }, { item: '嗜魂法杖', chance: 500 },
    { item: '龙纹剑', chance: 500 },
    { item: '怒斩', chance: 700 }, { item: '龙牙', chance: 700 },
    { item: '逍遥扇', chance: 700 },
    { item: '天衣无缝', chance: 300 }, { item: '赤魔甲', chance: 300 },
    { item: '绿魔甲', chance: 300 }, { item: '鬼面铠甲', chance: 300 },
    { item: '火龙魔衣', chance: 300 }, { item: '玄天宝衣', chance: 300 },
    { item: '绿色项链', chance: 200 }, { item: '恶魔铃铛', chance: 200 },
    { item: '灵魂项链', chance: 200 }, { item: '五玄项链', chance: 200 },
    { item: '力量戒指', chance: 200 }, { item: '泰坦戒指', chance: 200 },
    { item: '紫碧螺', chance: 200 }, { item: '五玄戒指', chance: 200 },
    { item: '黑铁头盔', chance: 200 }, { item: '骑士手镯', chance: 200 },
    { item: '阎罗手套', chance: 200 }, { item: '五玄手镯', chance: 200 },
    { item: '天务', chance: 300 }, { item: '逐日剑法', chance: 300 },
    { item: '流星火雨', chance: 300 }, { item: '召唤月灵', chance: 300 },
    { item: '魔血戒指', chance: 120 }, { item: '虹魔戒指', chance: 120 },
  ],
  // === 通天塔Boss专属掉落 (26-30层: 最高级) ===
  '洪荒之神': [
    { item: '金币', chance: 1, count: 40000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 1500 }, { item: '护身戒指', chance: 1500 },
    { item: '传送戒指', chance: 1500 }, { item: '复活戒指', chance: 1500 },
    { item: '火焰戒指', chance: 1500 }, { item: '防御戒指', chance: 1500 },
    { item: '超负载戒指', chance: 1500 }, { item: '记忆戒指', chance: 1500 },
    { item: '屠龙', chance: 400 }, { item: '嗜魂法杖', chance: 400 },
    { item: '龙纹剑', chance: 400 },
    { item: '怒斩', chance: 500 }, { item: '龙牙', chance: 500 },
    { item: '逍遥扇', chance: 500 },
    { item: '天衣无缝', chance: 250 }, { item: '赤魔甲', chance: 250 },
    { item: '绿魔甲', chance: 250 }, { item: '鬼面铠甲', chance: 250 },
    { item: '火龙魔衣', chance: 250 }, { item: '玄天宝衣', chance: 250 },
    { item: '绿色项链', chance: 180 }, { item: '恶魔铃铛', chance: 180 },
    { item: '灵魂项链', chance: 180 }, { item: '五玄项链', chance: 180 },
    { item: '力量戒指', chance: 180 }, { item: '泰坦戒指', chance: 180 },
    { item: '紫碧螺', chance: 180 }, { item: '五玄戒指', chance: 180 },
    { item: '黑铁头盔', chance: 180 }, { item: '骑士手镯', chance: 180 },
    { item: '阎罗手套', chance: 180 }, { item: '五玄手镯', chance: 180 },
    { item: '天务', chance: 240 }, { item: '逐日剑法', chance: 240 },
    { item: '流星火雨', chance: 240 }, { item: '召唤月灵', chance: 240 },
    { item: '魔血戒指', chance: 100 }, { item: '虹魔戒指', chance: 100 },
    { item: '勇猛宝玉', chance: 150 }, { item: '魔性宝玉', chance: 150 },
    { item: '仙界宝玉', chance: 150 }, { item: '守护宝玉', chance: 150 },
  ],
  '失落魔王': [
    { item: '金币', chance: 1, count: 42000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 1500 }, { item: '护身戒指', chance: 1500 },
    { item: '传送戒指', chance: 1500 }, { item: '复活戒指', chance: 1500 },
    { item: '火焰戒指', chance: 1500 }, { item: '防御戒指', chance: 1500 },
    { item: '超负载戒指', chance: 1500 }, { item: '记忆戒指', chance: 1500 },
    { item: '屠龙', chance: 400 }, { item: '嗜魂法杖', chance: 400 },
    { item: '龙纹剑', chance: 400 },
    { item: '怒斩', chance: 500 }, { item: '龙牙', chance: 500 },
    { item: '逍遥扇', chance: 500 },
    { item: '天衣无缝', chance: 250 }, { item: '赤魔甲', chance: 250 },
    { item: '绿魔甲', chance: 250 }, { item: '鬼面铠甲', chance: 250 },
    { item: '火龙魔衣', chance: 250 }, { item: '玄天宝衣', chance: 250 },
    { item: '绿色项链', chance: 180 }, { item: '恶魔铃铛', chance: 180 },
    { item: '灵魂项链', chance: 180 }, { item: '五玄项链', chance: 180 },
    { item: '力量戒指', chance: 180 }, { item: '泰坦戒指', chance: 180 },
    { item: '紫碧螺', chance: 180 }, { item: '五玄戒指', chance: 180 },
    { item: '黑铁头盔', chance: 180 }, { item: '骑士手镯', chance: 180 },
    { item: '阎罗手套', chance: 180 }, { item: '五玄手镯', chance: 180 },
    { item: '天务', chance: 240 }, { item: '逐日剑法', chance: 240 },
    { item: '流星火雨', chance: 240 }, { item: '召唤月灵', chance: 240 },
    { item: '魔血戒指', chance: 100 }, { item: '虹魔戒指', chance: 100 },
    { item: '勇猛宝玉', chance: 150 }, { item: '魔性宝玉', chance: 150 },
    { item: '仙界宝玉', chance: 150 }, { item: '守护宝玉', chance: 150 },
  ],
  '邀月': [
    { item: '金币', chance: 1, count: 45000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 1200 }, { item: '护身戒指', chance: 1200 },
    { item: '传送戒指', chance: 1200 }, { item: '复活戒指', chance: 1200 },
    { item: '火焰戒指', chance: 1200 }, { item: '防御戒指', chance: 1200 },
    { item: '超负载戒指', chance: 1200 }, { item: '记忆戒指', chance: 1200 },
    { item: '屠龙', chance: 350 }, { item: '嗜魂法杖', chance: 350 },
    { item: '龙纹剑', chance: 350 },
    { item: '怒斩', chance: 400 }, { item: '龙牙', chance: 400 },
    { item: '逍遥扇', chance: 400 },
    { item: '天衣无缝', chance: 200 }, { item: '赤魔甲', chance: 200 },
    { item: '绿魔甲', chance: 200 }, { item: '鬼面铠甲', chance: 200 },
    { item: '火龙魔衣', chance: 200 }, { item: '玄天宝衣', chance: 200 },
    { item: '绿色项链', chance: 150 }, { item: '恶魔铃铛', chance: 150 },
    { item: '灵魂项链', chance: 150 }, { item: '五玄项链', chance: 150 },
    { item: '力量戒指', chance: 150 }, { item: '泰坦戒指', chance: 150 },
    { item: '紫碧螺', chance: 150 }, { item: '五玄戒指', chance: 150 },
    { item: '黑铁头盔', chance: 150 }, { item: '骑士手镯', chance: 150 },
    { item: '阎罗手套', chance: 150 }, { item: '五玄手镯', chance: 150 },
    { item: '天务', chance: 180 }, { item: '逐日剑法', chance: 180 },
    { item: '流星火雨', chance: 180 }, { item: '召唤月灵', chance: 180 },
    { item: '魔血戒指', chance: 80 }, { item: '虹魔戒指', chance: 80 },
    { item: '勇猛宝玉', chance: 120 }, { item: '魔性宝玉', chance: 120 },
    { item: '仙界宝玉', chance: 120 }, { item: '守护宝玉', chance: 120 },
    { item: '制魔宝玉', chance: 120 }, { item: '集中宝玉', chance: 120 },
  ],
  '深渊': [
    { item: '金币', chance: 1, count: 48000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 1200 }, { item: '护身戒指', chance: 1200 },
    { item: '传送戒指', chance: 1200 }, { item: '复活戒指', chance: 1200 },
    { item: '火焰戒指', chance: 1200 }, { item: '防御戒指', chance: 1200 },
    { item: '超负载戒指', chance: 1200 }, { item: '记忆戒指', chance: 1200 },
    { item: '屠龙', chance: 300 }, { item: '嗜魂法杖', chance: 300 },
    { item: '龙纹剑', chance: 300 },
    { item: '怒斩', chance: 350 }, { item: '龙牙', chance: 350 },
    { item: '逍遥扇', chance: 350 },
    { item: '天衣无缝', chance: 180 }, { item: '赤魔甲', chance: 180 },
    { item: '绿魔甲', chance: 180 }, { item: '鬼面铠甲', chance: 180 },
    { item: '火龙魔衣', chance: 180 }, { item: '玄天宝衣', chance: 180 },
    { item: '绿色项链', chance: 120 }, { item: '恶魔铃铛', chance: 120 },
    { item: '灵魂项链', chance: 120 }, { item: '五玄项链', chance: 120 },
    { item: '力量戒指', chance: 120 }, { item: '泰坦戒指', chance: 120 },
    { item: '紫碧螺', chance: 120 }, { item: '五玄戒指', chance: 120 },
    { item: '黑铁头盔', chance: 120 }, { item: '骑士手镯', chance: 120 },
    { item: '阎罗手套', chance: 120 }, { item: '五玄手镯', chance: 120 },
    { item: '天务', chance: 150 }, { item: '逐日剑法', chance: 150 },
    { item: '流星火雨', chance: 150 }, { item: '召唤月灵', chance: 150 },
    { item: '魔血戒指', chance: 60 }, { item: '虹魔戒指', chance: 60 },
    { item: '勇猛宝玉', chance: 100 }, { item: '魔性宝玉', chance: 100 },
    { item: '仙界宝玉', chance: 100 }, { item: '守护宝玉', chance: 100 },
    { item: '制魔宝玉', chance: 100 }, { item: '集中宝玉', chance: 100 },
  ],
  '祭血心魔': [
    { item: '金币', chance: 1, count: 50000 },
    { item: '金创药(特量)', chance: 1 }, { item: '魔法药(特量)', chance: 1 },
    { item: '强效太阳水', chance: 1 },
    { item: '麻痹戒指', chance: 1000 }, { item: '护身戒指', chance: 1000 },
    { item: '传送戒指', chance: 1000 }, { item: '复活戒指', chance: 1000 },
    { item: '火焰戒指', chance: 1000 }, { item: '防御戒指', chance: 1000 },
    { item: '超负载戒指', chance: 1000 }, { item: '记忆戒指', chance: 1000 },
    { item: '屠龙', chance: 250 }, { item: '嗜魂法杖', chance: 250 },
    { item: '龙纹剑', chance: 250 },
    { item: '怒斩', chance: 300 }, { item: '龙牙', chance: 300 },
    { item: '逍遥扇', chance: 300 },
    { item: '天衣无缝', chance: 150 }, { item: '赤魔甲', chance: 150 },
    { item: '绿魔甲', chance: 150 }, { item: '鬼面铠甲', chance: 150 },
    { item: '火龙魔衣', chance: 150 }, { item: '玄天宝衣', chance: 150 },
    { item: '绿色项链', chance: 100 }, { item: '恶魔铃铛', chance: 100 },
    { item: '灵魂项链', chance: 100 }, { item: '五玄项链', chance: 100 },
    { item: '力量戒指', chance: 100 }, { item: '泰坦戒指', chance: 100 },
    { item: '紫碧螺', chance: 100 }, { item: '五玄戒指', chance: 100 },
    { item: '黑铁头盔', chance: 100 }, { item: '骑士手镯', chance: 100 },
    { item: '阎罗手套', chance: 100 }, { item: '五玄手镯', chance: 100 },
    { item: '天务', chance: 120 }, { item: '逐日剑法', chance: 120 },
    { item: '流星火雨', chance: 120 }, { item: '召唤月灵', chance: 120 },
    { item: '魔血戒指', chance: 50 }, { item: '虹魔戒指', chance: 50 },
    { item: '勇猛宝玉', chance: 80 }, { item: '魔性宝玉', chance: 80 },
    { item: '仙界宝玉', chance: 80 }, { item: '守护宝玉', chance: 80 },
    { item: '制魔宝玉', chance: 80 }, { item: '集中宝玉', chance: 80 },
  ],

};

// ==================== 二大陆（遮天篇）掉落表 ====================
// 爆率口径见 二大陆计划表.html §五/§六；小怪必须显式定义以避开 GENERIC_DROPS.high 回退

// --- 小怪共享掉落行 ---
const _c2Gold = { item: '金币', chance: 1, count: 1500 };
const _c2Pot = [{ item: '强效金创药', chance: 8 }, { item: '强效魔法药', chance: 8 }];
const _c2BasicAcc = [ // 基础首饰线 1/1500
    { item: '金戒指', chance: 1500 }, { item: '白金项链', chance: 1500 },
    { item: '黑檀项链', chance: 1500 }, { item: '竹笛', chance: 1500 },
    { item: '躲避项链', chance: 1500 },
  ];
const _c2SuitT2 = [ // 圣战/法神/天尊套 1/1500
    { item: '圣战头盔', chance: 1500 }, { item: '圣战项链', chance: 1500 },
    { item: '圣战手镯', chance: 1500 }, { item: '圣战戒指', chance: 1500 },
    { item: '圣战宝甲', chance: 1500 },
    { item: '法神头盔', chance: 1500 }, { item: '法神项链', chance: 1500 },
    { item: '法神手镯', chance: 1500 }, { item: '法神戒指', chance: 1500 },
    { item: '法神宝甲', chance: 1500 },
    { item: '天尊头盔', chance: 1500 }, { item: '天尊项链', chance: 1500 },
    { item: '天尊手镯', chance: 1500 }, { item: '天尊戒指', chance: 1500 },
    { item: '天尊宝甲', chance: 1500 },
  ];
const _c2Guangmang = [ // 光芒系列
    { item: '光芒项链', chance: 1500 }, { item: '光芒手镯', chance: 1500 },
    { item: '光芒戒指', chance: 1500 },
  ];
const _c2Shixue = [ // 嗜血系列
    { item: '嗜血战斧', chance: 2000 }, { item: '嗜血法杖', chance: 2000 },
    { item: '嗜血圣剑', chance: 2000 },
  ];
const _c2Tengyu = [ // 藤域系列
    { item: '藤域项链', chance: 2000 }, { item: '藤域手镯', chance: 2000 },
    { item: '藤域戒指', chance: 2000 },
  ];
const _c2QinglongArmor = [ // 白虎/朱雀/青龙盔甲
    { item: '白虎战甲', chance: 8000 }, { item: '朱雀魔袍', chance: 8000 },
    { item: '青龙道衣', chance: 8000 },
  ];
const _c2T6Weapon = [ // 屠龙三系武器
    { item: '圣战屠龙', chance: 8000 }, { item: '法神天魔', chance: 8000 },
    { item: '天尊圣纹', chance: 8000 },
  ];
const _c2ButterflyWeapon = [ // 蝴蝶武器
    { item: '蝴蝶战刃', chance: 8000 }, { item: '蝴蝶权杖', chance: 8000 },
    { item: '蝴蝶之扇', chance: 8000 },
  ];
const _c2ButterflyAcc = [ // 蝴蝶头盔/首饰
    { item: '蝴蝶战盔', chance: 8000 }, { item: '蝴蝶法冠', chance: 8000 },
    { item: '蝴蝶道冠', chance: 8000 },
    { item: '蝴蝶战链', chance: 8000 }, { item: '蝴蝶法链', chance: 8000 },
    { item: '蝴蝶道链', chance: 8000 },
    { item: '蝴蝶战镯', chance: 8000 }, { item: '蝴蝶法镯', chance: 8000 },
    { item: '蝴蝶道镯', chance: 8000 },
    { item: '蝴蝶战戒', chance: 8000 }, { item: '蝴蝶法戒', chance: 8000 },
    { item: '蝴蝶道戒', chance: 8000 },
  ];
const _c2Qilin = [ // 麒麟臂
    { item: '麒麟臂(神)', chance: 60000 }, { item: '麒麟臂(尊)', chance: 60000 },
  ];
const _c2Tejie = [ // 特殊戒指
    { item: '逆火麻痹', chance: 60000 }, { item: '护身精灵', chance: 60000 },
    { item: '永生指环', chance: 60000 },
  ];
const _c2ZhetianArmor = [ // 遮天套
    { item: '遮天盔甲', chance: 20000 }, { item: '遮天法袍', chance: 20000 },
    { item: '遮天圣衣', chance: 20000 },
  ];
const _c2GoldWeapon = [ // 黄金武器
    { item: '黄金锏', chance: 8000 }, { item: '黄金剑', chance: 8000 },
    { item: '黄金月', chance: 8000 },
  ];
const _c2GoldArmor = [ // 黄金盔甲
    { item: '黄金盔甲', chance: 8000 }, { item: '黄金法袍', chance: 8000 },
    { item: '黄金圣衣', chance: 8000 },
  ];
const _c2GoldAcc = [ // 黄金首饰
    { item: '黄金戒指', chance: 8000 },
  ];
const _c2Qijia = [{ item: '骑甲', chance: 8000 }];

// --- 区域小怪共享表 ---
const _zoneR2 = [_c2Gold, ..._c2Pot, ..._c2SuitT2];
const _zoneR3 = [_c2Gold, ..._c2Pot,
    { item: '力量戒指', chance: 6000 }, { item: '紫碧螺', chance: 6000 },
    { item: '泰坦戒指', chance: 6000 },
    { item: '裁决之杖', chance: 6000 }, { item: '龙纹剑', chance: 6000 },
    { item: '骨玉权杖', chance: 6000 },
  ];
const _zoneR4 = [_c2Gold, ..._c2Pot, ..._c2BasicAcc,
    { item: '喋血战刃', chance: 20000 }, { item: '喋血魔杖', chance: 20000 },
    { item: '喋血道剑', chance: 20000 },
  ];
const _zoneR5 = [_c2Gold, ..._c2Pot, ..._c2SuitT2.map(d => ({ ...d, chance: 6000 }))];
const _zoneR6 = [_c2Gold, ..._c2Pot, ..._c2BasicAcc,
    { item: '光芒项链', chance: 6000 },
  ];
const _zoneR7 = [_c2Gold, ..._c2Pot,
    { item: '考斯项链', chance: 6000 }, { item: '命运之链', chance: 6000 },
    { item: '迪斯项链', chance: 6000 },
    { item: '藤域项链', chance: 6000 }, { item: '藤域手镯', chance: 6000 },
    { item: '藤域戒指', chance: 6000 },
    { item: '木域项链', chance: 6000 }, { item: '木域手镯', chance: 6000 },
    { item: '木域戒指', chance: 6000 },
  ];
const _zoneR8 = [_c2Gold, ..._c2Pot];
const _zoneR9 = [_c2Gold, ..._c2Pot, ..._c2BasicAcc,
    { item: '霸者腰带', chance: 20000 }, { item: '邪者腰带', chance: 20000 },
    { item: '道者腰带', chance: 20000 }, { item: '布靴', chance: 20000 },
  ];
const _zoneR10 = [_c2Gold, ..._c2Pot,
    { item: '藤域项链', chance: 6000 }, { item: '藤域手镯', chance: 6000 },
    { item: '藤域戒指', chance: 6000 },
    { item: '木域项链', chance: 6000 }, { item: '木域手镯', chance: 6000 },
    { item: '木域戒指', chance: 6000 },
    { item: '神域项链', chance: 6000 }, { item: '神域手镯', chance: 6000 },
    { item: '神域戒指', chance: 6000 },
    ..._c2Guangmang,
  ];
const _zoneR11R13 = [_c2Gold, ..._c2Pot, ..._c2BasicAcc];
const _zoneR12 = [_c2Gold, ..._c2Pot];
const _zoneR14 = [_c2Gold, ..._c2Pot, ..._c2T6Weapon,
    { item: '葬神头盔', chance: 20000 },
  ];
const _zoneR15 = [_c2Gold, ..._c2Pot, ..._c2T6Weapon];
const _zoneR16R17 = [_c2Gold, ..._c2Pot, ..._c2ZhetianArmor];

// --- BOSS 掉落表 ---
const _bossSMPW = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2Guangmang.map(d => ({ ...d, chance: 2000 })),
    ..._c2Shixue, { item: '考斯项链', chance: 2000 },
  ];
const _bossZTWM = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2Guangmang.map(d => ({ ...d, chance: 2000 })), ..._c2Shixue,
  ];
const _bossZTZM = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2Guangmang.map(d => ({ ...d, chance: 2000 })),
    { item: '战神戒指', chance: 2000 },
    { item: '邪恶头冠', chance: 2000 }, { item: '太阳头盔', chance: 2000 },
    { item: '凤者之冠', chance: 2000 }, ..._c2Shixue,
  ];
const _bossZMJH = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2QinglongArmor, ..._c2Shixue,
  ];
const _bossYH = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2Qilin, ..._c2QinglongArmor, ..._c2Shixue,
  ];
const _bossNMSW = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2ZhetianArmor, ..._c2ButterflyWeapon,
    { item: '霸者腰带', chance: 8000 }, { item: '邪者腰带', chance: 8000 },
    { item: '道者腰带', chance: 8000 }, { item: '布靴', chance: 8000 },
    ..._c2ButterflyAcc,
  ];
const _bossDCJZ = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '覆云战衣', chance: 8000 }, { item: '古迹战甲', chance: 8000 },
    { item: '墨龙之翼', chance: 8000 }, { item: '墨龙之羽', chance: 8000 },
    ..._c2QinglongArmor, ..._c2Shixue, ..._c2Tengyu,
  ];
const _bossHAJZ = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 }, ..._c2Tejie,
    ..._c2T6Weapon, ..._c2Qijia, ..._c2ButterflyWeapon,
  ];
const _bossSYW = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2QinglongArmor, ..._c2Shixue,
  ];
const _bossR8 = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 }, { item: '暴君吊坠', chance: 20000 },
    ..._c2Qilin, { item: '火龙之心', chance: 60000 }, ..._c2Tejie,
    ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
  ];
const _bossR9 = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '霸者腰带', chance: 8000 }, { item: '邪者腰带', chance: 8000 },
    { item: '道者腰带', chance: 8000 }, { item: '布靴', chance: 8000 },
    ..._c2Qilin, ..._c2T6Weapon, ..._c2Qijia,
  ];
const _bossMZZZ = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '暴君吊坠', chance: 20000 }, ..._c2Qilin, ..._c2Tejie,
    ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
  ];
const _bossMFHF = [_c2Gold, { item: '金币', chance: 1, count: 30000 }, ..._c2Pot,
    ..._c2T6Weapon, ..._c2Qijia, ..._c2ButterflyWeapon,
  ];
const _bossHQNJ = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '潘夜隐戒', chance: 8000 }, ..._c2QinglongArmor,
    ..._c2Shixue, ..._c2Tengyu,
  ];
const _bossAZNM = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '隐身戒指', chance: 8000 }, ..._c2Tejie,
    ..._c2T6Weapon, ..._c2Qijia, ..._c2ButterflyWeapon,
  ];
const _bossXMJZ = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    ..._c2QinglongArmor, ..._c2Shixue, ..._c2Tengyu,
  ];
const _bossTXEM = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天左手', chance: 20000 }, { item: '遮天右手', chance: 20000 },
    { item: '遮天神石', chance: 60000 },
    ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
  ];
const _bossQSGY = [_c2Gold, { item: '金币', chance: 1, count: 40000 }, ..._c2Pot,
    { item: '暴君吊坠', chance: 20000 }, ..._c2Qilin,
    { item: '火龙之心', chance: 60000 }, ..._c2ButterflyWeapon,
  ];
const _bossGYJXXM = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 }, ..._c2Tejie,
    ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
    { item: '蝴蝶戒指', chance: 8000 },
  ];
const _bossWEZM = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 }, ..._c2Qilin,
    { item: '火龙之心', chance: 60000 }, ..._c2GoldAcc, ..._c2GoldWeapon,
  ];
const _bossGYFL = [_c2Gold, { item: '金币', chance: 1, count: 30000 }, ..._c2Pot,
    ..._c2QinglongArmor, ..._c2Shixue, ..._c2Qijia,
  ];
const _bossZSBZ = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '苍茫神翼', chance: 60000 }, { item: '苍茫神石', chance: 60000 },
    { item: '葬神头盔', chance: 20000 }, ..._c2Qijia, ..._c2ButterflyWeapon,
  ];
const _bossJLEX = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '葬神头盔', chance: 20000 }, { item: '火龙之心', chance: 60000 },
    { item: '遮天左手', chance: 20000 }, { item: '遮天右手', chance: 20000 },
    ..._c2GoldAcc, { item: '黄金锏', chance: 8000 },
  ];
const _bossBYMW = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '苍茫神翼', chance: 60000 }, { item: '苍茫神石', chance: 60000 },
    { item: '遮天神石', chance: 60000 }, { item: '火龙之心', chance: 60000 },
    { item: '遮天左手', chance: 60000 }, { item: '遮天右手', chance: 60000 },
    ..._c2GoldAcc, ..._c2GoldWeapon,
  ];
const _bossCYMS = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 }, ..._c2Qilin,
    { item: '火龙之心', chance: 60000 },
    ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
  ];
const _bossLHLX = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '苍茫神翼', chance: 60000 }, { item: '苍茫神石', chance: 60000 },
    { item: '遮天神石', chance: 60000 },
    { item: '遮天左手', chance: 60000 }, { item: '遮天右手', chance: 60000 },
    { item: '火龙之心', chance: 60000 },
    ..._c2GoldWeapon, ..._c2GoldArmor,
  ];
const _bossSWDG = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 },
    { item: '遮天左手', chance: 60000 }, { item: '遮天右手', chance: 60000 },
    ..._c2GoldWeapon, ..._c2GoldArmor,
  ];
const _bossSWKB = [_c2Gold, { item: '金币', chance: 1, count: 80000 }, ..._c2Pot,
    { item: '遮天左手', chance: 40000 }, { item: '遮天右手', chance: 40000 },
    { item: '火龙之心', chance: 40000 },
    { item: '天晶战刃', chance: 20000 }, { item: '虎魄之剑', chance: 20000 },
    { item: '太虚圣刀', chance: 20000 },
    { item: '战力无双', chance: 20000 }, { item: '道临天下', chance: 20000 },
  ];
const _bossR17Elite = [_c2Gold, { item: '金币', chance: 1, count: 30000 }, ..._c2Pot,
    ..._c2T6Weapon, ..._c2Qijia, ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
  ];
const _bossR18 = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 }, { item: '暴君吊坠', chance: 20000 },
    ..._c2Qilin, { item: '火龙之心', chance: 60000 },
    ..._c2ButterflyWeapon, ..._c2ZhetianArmor,
  ];
const _bossDMZH = [_c2Gold, { item: '金币', chance: 1, count: 50000 }, ..._c2Pot,
    { item: '遮天神石', chance: 60000 },
    { item: '遮天左手', chance: 60000 }, { item: '遮天右手', chance: 60000 },
    ..._c2Qilin, { item: '火龙之心', chance: 60000 },
    ..._c2GoldAcc, ..._c2GoldWeapon,
  ];
const _bossHLS = [_c2Gold, { item: '金币', chance: 1, count: 100000 }, ..._c2Pot,
    { item: '遮天神石', chance: 40000 }, { item: '火龙之心', chance: 40000 },
    { item: '遮天左手', chance: 40000 }, { item: '遮天右手', chance: 40000 },
    ..._c2GoldWeapon, ..._c2GoldArmor,
  ];

// --- R1 桃源（入门档，无装备产出）---
DROPS['桃源刀兵'] = [_c2Gold, ..._c2Pot];
DROPS['桃源锤兵'] = [_c2Gold, ..._c2Pot];
DROPS['桃源枪兵'] = [_c2Gold, ..._c2Pot];
DROPS['桃源恶尸'] = [_c2Gold, ..._c2Pot];
DROPS['桃源领主'] = [_c2Gold, { item: '金币', chance: 1, count: 20000 }, ..._c2Pot, ..._c2BasicAcc];

// --- 二大陆区域小怪循环赋值 ---
([
  ['遮天红野猪', '遮天黑野猪', '遮天蝎蛇', '遮天楔蛾', '遮天黑色恶蛆', '遮天白野猪'], _zoneR2,
  ['遮天祖玛弓箭手', '遮天祖玛雕像', '遮天祖玛卫士', '遮天沃玛卫士'], _zoneR3,
  ['工蚁', '兵蚁', '毒蚁', '火蚁'], _zoneR4,
  ['诺玛战士', '诺玛法师', '诺玛道士', '诺玛战神', '诺玛法神', '诺玛道神'], _zoneR5,
  ['炽热之眼', '大地之眼', '寒冰之眼', '沼泽之眼', '巨毒蛇蝎', '巨毒野猪', '镇谷魔兽'], _zoneR6,
  ['黑暗战士', '黑暗刀兵', '黑暗斧兵', '黑暗锥兵', '黑暗火投手', '舔血精兽', '半月经轮', '黑暗刺魔', '黑暗鬼魔', '黑暗妖女'], _zoneR7,
  ['古墓虎卫', '古墓亡魂', '古墓鹰卫', '古墓巨斧怪', '古墓巨剑怪', '古墓连弩怪', '古墓镰刀怪', '天晶翼魔'], _zoneR8,
  ['骷髅领主', '蝎蛇领主', '沃玛领主', '野猪领主'], _zoneR9,
  ['魔兽刀兵', '魔兽锤兵', '魔兽破甲兵', '魔兽射手', '魔兽巨蛾'], _zoneR10,
  ['潘夜斗士', '潘夜侍卫', '潘夜战士', '潘夜祭祀', '潘夜将军', '潘夜祭司'], _zoneR11R13,
  ['血魔骑士', '血魔卫士', '血魔蝙蝠', '血魔恶龙', '血魔箭兵', '血魔将军'], _zoneR12,
  ['鬼域僵尸', '鬼域枪兵', '鬼域卫士', '鬼域蜘蛛', '鬼域祭祀', '鬼域将军'], _zoneR11R13,
  ['葬神判官', '葬神修罗', '葬神爪牙', '葬神恶龙'], _zoneR14,
  ['冰美', '冰妖', '冰原枪兵', '冰原战士', '冰原寒冰魔', '冰原五毒魔', '冰原战将'], _zoneR15,
  ['白发魔兽', '金甲骑士', '死亡收割'], _zoneR16R17,
  ['龙皇赤凰', '龙皇火法', '死亡法神', '死亡悍将'], _zoneR16R17,
  ['幻海守护者', '凶冥守护者', '炎魔守护者'], [_c2Gold, { item: '金币', chance: 1, count: 3000 }, ..._c2Pot],
]).forEach(([name, table]) => { DROPS[name] = table; });

// --- 二大陆 BOSS 循环赋值 ---
([
  ['遮天石墓尸王', _bossSMPW], ['遮天沃玛教主', _bossZTWM],
  ['遮天祖玛教主', _bossZTZM], ['遮天祖玛教皇', _bossZMJH],
  ['蚁后', _bossYH],
  ['诺玛战王', _bossNMSW], ['诺玛法王', _bossNMSW], ['诺玛道王', _bossNMSW],
  ['毒蟾教主', _bossDCJZ],
  ['黑暗教主', _bossHAJZ], ['蛇妖王', _bossSYW],
  ['铁血魔王', _bossR8], ['白骨坟守', _bossR8], ['天晶聚魂石', _bossR8], ['古墓石像', _bossR8],
  ['天晶左护法', _bossMFHF], ['天晶右护法', _bossMFHF],
  ['冥王', _bossR9], ['宫殿神像', _bossR9],
  ['魔兽之主', _bossMZZZ], ['魔兽左护法', _bossMFHF], ['魔兽右护法', _bossMFHF],
  ['黄泉教主', _bossHQNJ], ['牛魔教主', _bossHQNJ], ['暗之牛魔教主', _bossAZNM],
  ['血魔教主', _bossXMJZ], ['天下恶魔', _bossTXEM], ['千手观音', _bossQSGY], ['地狱修罗', _bossQSGY],
  ['鬼域金刚', _bossGYJXXM], ['鬼域血魔', _bossGYJXXM], ['鬼域法老', _bossGYFL], ['万恶之魔', _bossWEZM],
  ['葬神霸主', _bossZSBZ], ['鸠罗恶相', _bossJLEX],
  ['冰原魔王', _bossBYMW], ['蚩尤魔兽', _bossCYMS],
  ['龙皇龙邪', _bossLHLX], ['死亡毒寡', _bossSWDG], ['死亡魁拔', _bossSWKB],
  ['幻海之灵', _bossR18], ['凶冥教主', _bossR18], ['炎魔领主', _bossR18], ['地魔之核', _bossDMZH],
  ['火龙神', _bossHLS],
]).forEach(([name, table]) => { DROPS[name] = table; });
// 通用掉落模板(按怪物等级)
const GENERIC_DROPS = {
  low: [ // 1-10级怪物
    { item: '金币', chance: 2, count: 20 },
    { item: '金创药(小量)', chance: 10 },
    { item: '木剑', chance: 800 }, { item: '匕首', chance: 800 },
    { item: '布衣', chance: 300 },
    { item: '金项链', chance: 1000 }, { item: '古铜戒指', chance: 1000 },
    { item: '铁手镯', chance: 1000 }, { item: '玻璃戒指', chance: 1200 },
  ],
  mid: [ // 11-20级怪物
    { item: '金币', chance: 2, count: 80 },
    { item: '金创药(中量)', chance: 8 },
    { item: '魔法药(中量)', chance: 8 },
    { item: '基本剑术', chance: 900 }, { item: '火球术', chance: 900 },
    { item: '治愈术', chance: 900 },
    { item: '攻杀剑术', chance: 3000 }, { item: '大火球', chance: 3000 },
    { item: '施毒术', chance: 3000 },
    { item: '抗拒火环', chance: 2400 }, { item: '精神力战法', chance: 2400 },
    { item: '隐身术', chance: 3600 }, { item: '召唤骷髅', chance: 3600 },
    { item: '修罗', chance: 3000 }, { item: '凝霜', chance: 3000 },
    { item: '珊瑚戒指', chance: 2000 }, { item: '蓝翡翠项链', chance: 2000 },
    { item: '重盔甲', chance: 2000 }, { item: '魔法长袍', chance: 2000 },
  ],
  high: [ // 21+级怪物
    { item: '金币', chance: 1, count: 400 },
    { item: '强效金创药', chance: 5 },
    { item: '强效魔法药', chance: 5 },
    { item: '刺杀剑术', chance: 1500 }, { item: '雷电术', chance: 1500 },
    { item: '灵魂火符', chance: 1500 },
    { item: '半月弯刀', chance: 4500 }, { item: '火墙', chance: 4500 },
    { item: '神圣战甲术', chance: 4500 },
    { item: '地狱雷光', chance: 6000 }, { item: '爆裂火焰', chance: 6000 },
    { item: '气功波', chance: 6000 }, { item: '寒冰掌', chance: 6000 },
    { item: '雷霆剑法', chance: 9000 }, { item: '嗜血术', chance: 9000 },
    { item: '无极真气', chance: 9000 }, { item: '召唤月灵', chance: 9000 },
    { item: '炼狱', chance: 4000 }, { item: '魔杖', chance: 4000 },
    { item: '银蛇', chance: 4000 },
    { item: '裁决之杖', chance: 5000 }, { item: '骨玉权杖', chance: 5000 },
    { item: '无极棍', chance: 5000 },
    { item: '屠龙', chance: 8000 }, { item: '嗜魂法杖', chance: 8000 },
    { item: '龙纹剑', chance: 8000 },
    { item: '幽灵项链', chance: 2000 }, { item: '龙之戒指', chance: 2000 },
    { item: '战神盔甲', chance: 2000 }, { item: '恶魔长袍', chance: 2000 },
    { item: '幽灵战衣', chance: 2000 },
    { item: '力量戒指', chance: 4000 }, { item: '泰坦戒指', chance: 4000 },
    { item: '紫碧螺', chance: 4000 },
    { item: '绿色项链', chance: 4000 }, { item: '恶魔铃铛', chance: 4000 },
    { item: '灵魂项链', chance: 4000 },
    { item: '天务', chance: 15000 }, { item: '逐日剑法', chance: 15000 },
    { item: '流星火雨', chance: 15000 },
  ]
};
