// 装备与物品数据 - 严格基于服务端 GEEM2.db StdItems表
// 字段说明: atk=DC(攻击), mc=MC(魔法), sc=SC(道术), def=AC(防御), magDef=MAC(魔御)
// 等级和属性值均取自StdItems表NeedLevel/Dc/Dc2/Mc/Mc2/Sc/Sc2/Ac/Ac2/Mac/Mac2字段
const ITEMS = {
  // === 武器 ===
  '木剑': { type: 'weapon', atk: [2, 5], level: 1, job: 'all' },
  '匕首': { type: 'weapon', atk: [4, 5], level: 2, job: 'all' },
  '乌木剑': { type: 'weapon', atk: [4, 8], mc: [0, 1], level: 4, job: 'all' },
  '青铜剑': { type: 'weapon', atk: [3, 7], level: 5, job: 'warrior' },
  '破魂': { type: 'weapon', atk: [8, 10], def: [0, 2], level: 20, job: 'all' },
  '罗刹': { type: 'weapon', atk: [0, 15], level: 15, job: 'warrior' },
  '斩马刀': { type: 'weapon', atk: [5, 15], level: 20, job: 'warrior' },
  '偃月': { type: 'weapon', atk: [4, 10], mc: [1, 3], level: 20, job: 'mage' },
  '降魔': { type: 'weapon', atk: [6, 11], sc: [1, 2], def: [0, 1], level: 20, job: 'taoist' },
  '修罗': { type: 'weapon', atk: [2, 20], level: 22, job: 'warrior' },
  '凝霜': { type: 'weapon', atk: [10, 13], level: 25, job: 'warrior' },
  '炼狱': { type: 'weapon', atk: [0, 27], level: 26, job: 'warrior' },
  '魔杖': { type: 'weapon', atk: [5, 9], mc: [2, 4], level: 26, job: 'mage' },
  '银蛇': { type: 'weapon', atk: [7, 14], sc: [1, 3], def: [0, 1], level: 26, job: 'taoist' },
  '井中月': { type: 'weapon', atk: [7, 22], magDef: [0, 12], level: 30, job: 'warrior' },
  '血饮': { type: 'weapon', atk: [6, 16], mc: [2, 3], def: [0, 5], level: 27, job: 'mage' },
  '裁决之杖': { type: 'weapon', atk: [0, 33], level: 30, job: 'warrior' },
  '骨玉权杖': { type: 'weapon', atk: [6, 12], mc: [1, 7], level: 30, job: 'mage' },
  '无极棍': { type: 'weapon', atk: [2, 18], sc: [2, 4], def: [0, 1], level: 29, job: 'taoist' },
  '屠龙': { type: 'weapon', atk: [5, 40], level: 40, job: 'warrior' },
  '嗜魂法杖': { type: 'weapon', atk: [6, 13], mc: [2, 10], level: 40, job: 'mage' },
  '龙纹剑': { type: 'weapon', atk: [8, 22], sc: [3, 5], def: [0, 1], level: 40, job: 'taoist' },
  '怒斩': { type: 'weapon', atk: [5, 16], mc: [1, 8], level: 36, job: 'warrior' },
  '龙牙': { type: 'weapon', atk: [5, 32], level: 36, job: 'mage' },
  '逍遥扇': { type: 'weapon', atk: [2, 16], sc: [3, 6], def: [0, 2], level: 36, job: 'taoist' },
  '火血匕': { type: 'weapon', atk: [9, 15], def: [0, 2], magDef: [0, 12], level: 28, job: 'all' },
  '青雷': { type: 'weapon', mc: [2, 3], level: 22, job: 'taoist' },
  // 以下为掉落表中存在但此前漏定义的物品，属性取自服务端 StdItems 表
  '短剑': { type: 'weapon', atk: [2, 10], level: 7, job: 'all' },
  '铁剑': { type: 'weapon', atk: [5, 9], level: 10, job: 'all' },
  '八荒': { type: 'weapon', atk: [4, 12], level: 15, job: 'warrior' },
  '半月': { type: 'weapon', atk: [5, 10], mc: [1, 1], level: 15, job: 'mage' },
  '海魂': { type: 'weapon', atk: [3, 10], mc: [1, 2], level: 15, job: 'mage' },
  '凌风': { type: 'weapon', atk: [6, 12], level: 19, job: 'warrior' },
  '祈祷之刃': { type: 'weapon', atk: [8, 20], def: [0, 3], magDef: [0, 1], level: 20, job: 'warrior' },
  '祖玛裁决之杖': { type: 'weapon', atk: [0, 33], magDef: [0, 2], level: 29, job: 'warrior' },
  '祖玛骨玉权杖': { type: 'weapon', atk: [6, 12], mc: [1, 6], level: 29, job: 'mage' },
  '祖玛无极棍': { type: 'weapon', atk: [2, 18], sc: [2, 4], def: [0, 1], level: 29, job: 'taoist' },
  '太极慧剑': { type: 'weapon', atk: [8, 31], sc: [3, 10], def: [0, 1], level: 43, job: 'taoist' },
  '映邪天神': { type: 'weapon', atk: [7, 25], mc: [3, 13], level: 43, job: 'mage' },
  '独孤九剑': { type: 'weapon', atk: [6, 50], level: 43, job: 'warrior' },
  // === 衣服 ===
  '布衣': { type: 'armor', def: [2, 2], level: 1, job: 'all' },
  '轻型盔甲': { type: 'armor', def: [3, 3], magDef: [1, 2], level: 11, job: 'all' },
  '中型盔甲': { type: 'armor', def: [3, 5], magDef: [1, 2], level: 16, job: 'all' },
  '重盔甲': { type: 'armor', def: [4, 7], magDef: [2, 3], level: 22, job: 'warrior' },
  '魔法长袍': { type: 'armor', def: [3, 5], magDef: [3, 4], level: 22, job: 'mage' },
  '灵魂战衣': { type: 'armor', def: [3, 6], magDef: [3, 3], level: 22, job: 'taoist' },
  '战神盔甲': { type: 'armor', def: [5, 15], magDef: [3, 4], level: 33, job: 'warrior' },
  '恶魔长袍': { type: 'armor', def: [3, 10], magDef: [5, 6], level: 33, job: 'mage' },
  '幽灵战衣': { type: 'armor', def: [3, 12], magDef: [4, 5], level: 33, job: 'taoist' },
  // 以下衣服服务端StdItems无同名数据，保留游戏设定数值
  '灵晶甲胄': { type: 'armor', def: [6, 12], magDef: [2, 4], level: 20, job: 'warrior' },
  '鬼面铠甲': { type: 'armor', def: [8, 16], magDef: [3, 5], level: 25, job: 'warrior' },
  '火龙魔衣': { type: 'armor', def: [6, 12], magDef: [5, 10], level: 25, job: 'mage' },
  '玄天宝衣': { type: 'armor', def: [7, 14], magDef: [4, 8], level: 25, job: 'taoist' },
  '天衣无缝': { type: 'armor', def: [10, 20], magDef: [4, 6], level: 30, job: 'warrior' },
  '赤魔甲': { type: 'armor', def: [8, 16], magDef: [6, 12], level: 30, job: 'mage' },
  '绿魔甲': { type: 'armor', def: [9, 18], magDef: [5, 10], level: 30, job: 'taoist' },
  '青魔甲': { type: 'armor', def: [11, 22], magDef: [4, 6], level: 30, job: 'warrior' },
  // 圣战/法神/天尊宝甲（官方1.80经典数值，服务端数据库未收录）
  '圣战宝甲': { type: 'armor', def: [8, 15], magDef: [4, 8], level: 40, job: 'warrior' },
  '法神宝甲': { type: 'armor', def: [6, 12], magDef: [5, 9], level: 40, job: 'mage' },
  '天尊宝甲': { type: 'armor', def: [7, 13], magDef: [4, 8], level: 40, job: 'taoist' },
  // === 头盔 ===
  '青铜头盔': { type: 'helmet', def: [0, 1], level: 10, job: 'all' },
  '骷髅头盔': { type: 'helmet', def: [2, 3], level: 30, job: 'all' },
  '道士头盔': { type: 'helmet', def: [1, 2], magDef: [2, 3], level: 24, job: 'all' },
  '金萤帽': { type: 'helmet', def: [1, 1], mc: [0, 1], level: 17, job: 'all' },
  '金铜头盔': { type: 'helmet', def: [1, 1], magDef: [1, 2], level: 20, job: 'all' },
  '钢铁头盔': { type: 'helmet', def: [1, 4], magDef: [1, 1], level: 33, job: 'all' },
  '记忆头盔': { type: 'helmet', def: [3, 3], level: 26, job: 'all' },
  '勇士头盔': { type: 'helmet', def: [0, 6], magDef: [1, 3], level: 37, job: 'all' },
  '黑铁头盔': { type: 'helmet', def: [2, 6], magDef: [2, 3], level: 46, job: 'all' },
  '英雄头盔': { type: 'helmet', def: [3, 7], magDef: [2, 3], level: 40, job: 'warrior' },
  '贤人帽': { type: 'helmet', def: [2, 3], magDef: [3, 3], mc: [1, 2], level: 40, job: 'mage' },
  '通天冠': { type: 'helmet', def: [3, 4], magDef: [2, 2], sc: [1, 2], level: 40, job: 'taoist' },
  '祈祷头盔': { type: 'helmet', def: [3, 4], magDef: [1, 2], level: 18, job: 'all' },
  '圣战头盔': { type: 'helmet', def: [4, 5], magDef: [2, 3], atk: [0, 1], level: 40, job: 'warrior' },
  '法神头盔': { type: 'helmet', def: [4, 4], magDef: [1, 2], mc: [0, 1], level: 28, job: 'mage' },
  '天尊头盔': { type: 'helmet', def: [4, 4], magDef: [1, 2], sc: [0, 1], level: 25, job: 'taoist' },
  // === 项链 ===
  '金项链': { type: 'necklace', magDef: [0, 1], level: 2, job: 'all' },
  '传统项链': { type: 'necklace', def: [0, 1], level: 3, job: 'all' },
  '白色虎齿项链': { type: 'necklace', def: [0, 2], sc: [0, 1], level: 11, job: 'all' },
  '白金项链': { type: 'necklace', mc: [0, 2], level: 10, job: 'all' },
  '竹笛': { type: 'necklace', sc: [1, 3], level: 24, job: 'all' },
  '放大镜': { type: 'necklace', mc: [1, 3], level: 24, job: 'mage' },
  '蓝翡翠项链': { type: 'necklace', atk: [2, 2], level: 23, job: 'warrior' },
  '幽灵项链': { type: 'necklace', atk: [0, 5], level: 24, job: 'mage' },
  '生命项链': { type: 'necklace', mc: [1, 5], level: 25, job: 'taoist' },
  '天珠项链': { type: 'necklace', sc: [1, 5], level: 22, job: 'taoist' },
  '记忆项链': { type: 'necklace', atk: [2, 4], level: 26, job: 'warrior' },
  '绿色项链': { type: 'necklace', atk: [2, 5], level: 37, job: 'warrior' },
  '恶魔铃铛': { type: 'necklace', mc: [0, 7], level: 27, job: 'mage' },
  '灵魂项链': { type: 'necklace', sc: [1, 6], mc: [0, 0], level: 23, job: 'taoist' },
  '五玄项链': { type: 'necklace', mc: [1, 4], level: 34, job: 'all' },
  '灵力项链': { type: 'necklace', sc: [2, 4], level: 10, job: 'taoist' },
  '祈祷项链': { type: 'necklace', sc: [0, 4], level: 15, job: 'taoist' },
  '紫晶石项链': { type: 'necklace', atk: [3, 3], level: 34, job: 'warrior' },
  '破碎项链': { type: 'necklace', atk: [0, 5], level: 35, job: 'warrior' },
  '水波项链': { type: 'necklace', atk: [2, 6], level: 40, job: 'warrior' },
  '金刚铃项链': { type: 'necklace', mc: [1, 7], level: 40, job: 'mage' },
  '镇魂项链': { type: 'necklace', sc: [1, 8], def: [0, 2], level: 40, job: 'taoist' },
  '圣战项链': { type: 'necklace', atk: [3, 6], level: 40, job: 'warrior' },
  '法神项链': { type: 'necklace', mc: [1, 8], def: [1, 2], level: 28, job: 'mage' },
  '天尊项链': { type: 'necklace', sc: [2, 7], def: [1, 2], level: 25, job: 'taoist' },
  // === 手镯 ===
  '小手镯': { type: 'bracelet', magDef: [0, 1], level: 5, job: 'all' },
  '皮制手套': { type: 'bracelet', def: [0, 1], level: 7, job: 'all' },
  '银手镯': { type: 'bracelet', magDef: [0, 1], level: 7, job: 'all' },
  '铁手镯': { type: 'bracelet', def: [0, 1], level: 3, job: 'all' },
  '钢手镯': { type: 'bracelet', def: [0, 1], magDef: [0, 1], level: 8, job: 'all' },
  '大手镯': { type: 'bracelet', def: [1, 1], level: 9, job: 'all' },
  '黑檀手镯': { type: 'bracelet', mc: [0, 1], level: 19, job: 'mage' },
  '道士手镯': { type: 'bracelet', sc: [0, 1], level: 19, job: 'taoist' },
  '金手镯': { type: 'bracelet', atk: [0, 1], magDef: [2, 3], level: 23, job: 'all' },
  '死神手套': { type: 'bracelet', atk: [1, 2], level: 22, job: 'warrior' },
  '黑铁手镯': { type: 'bracelet', def: [0, 1], magDef: [1, 1], atk: [0, 1], mc: [0, 1], sc: [0, 1], level: 27, job: 'all' },
  '思贝儿手镯': { type: 'bracelet', mc: [0, 2], level: 26, job: 'mage' },
  '三眼手镯': { type: 'bracelet', sc: [0, 2], level: 22, job: 'taoist' },
  '夏普儿手镯': { type: 'bracelet', def: [0, 2], level: 16, job: 'all' },
  '辟邪手镯': { type: 'bracelet', magDef: [0, 2], level: 19, job: 'all' },
  '幽灵手套': { type: 'bracelet', def: [0, 3], level: 25, job: 'mage' },
  '钢铁手套': { type: 'bracelet', def: [0, 3], atk: [0, 2], level: 35, job: 'warrior' },
  '骑士手镯': { type: 'bracelet', atk: [2, 2], level: 39, job: 'warrior' },
  '龙之手镯': { type: 'bracelet', mc: [0, 3], level: 28, job: 'mage' },
  '心灵手镯': { type: 'bracelet', sc: [1, 2], level: 24, job: 'taoist' },
  '阎罗手套': { type: 'bracelet', def: [0, 4], level: 30, job: 'warrior' },
  '五玄手镯': { type: 'bracelet', def: [0, 2], mc: [0, 2], level: 34, job: 'all' },
  '祈祷手镯': { type: 'bracelet', atk: [0, 2], level: 15, job: 'warrior' },
  '魔血手镯': { type: 'bracelet', sc: [1, 1], level: 33, job: 'taoist' },
  '虹魔手镯': { type: 'bracelet', sc: [0, 2], level: 33, job: 'taoist' },
  '白驼臂铠': { type: 'bracelet', atk: [0, 3], def: [0, 2], magDef: [0, 2], level: 37, job: 'warrior' },
  '魂锁护腕': { type: 'bracelet', mc: [0, 4], def: [0, 2], level: 37, job: 'mage' },
  '太极护腕': { type: 'bracelet', sc: [1, 3], atk: [1, 1], def: [0, 2], level: 37, job: 'taoist' },
  '圣战手镯': { type: 'bracelet', atk: [2, 3], def: [0, 1], level: 40, job: 'warrior' },
  '法神手镯': { type: 'bracelet', mc: [0, 4], def: [0, 1], level: 28, job: 'mage' },
  '天尊手镯': { type: 'bracelet', sc: [1, 4], def: [1, 2], level: 25, job: 'taoist' },
  // === 戒指 ===
  '玻璃戒指': { type: 'ring', sc: [0, 1], level: 7, job: 'all' },
  '六角戒指': { type: 'ring', mc: [0, 1], level: 7, job: 'mage' },
  '牛角戒指': { type: 'ring', def: [0, 1], atk: [0, 1], level: 9, job: 'all' },
  '白玉戒指': { type: 'ring', def: [0, 1], magDef: [0, 1], sc: [0, 1], level: 7, job: 'all' },
  '古铜戒指': { type: 'ring', atk: [0, 1], level: 3, job: 'all' },
  '黑色水晶戒指': { type: 'ring', atk: [0, 2], level: 20, job: 'all' },
  '蛇眼戒指': { type: 'ring', mc: [0, 2], level: 20, job: 'mage' },
  '珍珠戒指': { type: 'ring', sc: [0, 2], level: 20, job: 'taoist' },
  '生铁戒指': { type: 'ring', def: [0, 2], mc: [0, 1], level: 9, job: 'all' },
  '金戒指': { type: 'ring', magDef: [3, 3], atk: [1, 1], mc: [1, 1], sc: [1, 1], level: 20, job: 'all' },
  '珊瑚戒指': { type: 'ring', atk: [0, 4], level: 25, job: 'warrior' },
  '降妖除魔戒指': { type: 'ring', magDef: [0, 4], atk: [1, 2], mc: [1, 2], sc: [1, 2], level: 25, job: 'taoist' },
  '龙之戒指': { type: 'ring', atk: [0, 5], sc: [0, 1], level: 37, job: 'mage' },
  '红宝石戒指': { type: 'ring', mc: [0, 4], level: 17, job: 'mage' },
  '铂金戒指': { type: 'ring', sc: [0, 4], level: 17, job: 'taoist' },
  '力量戒指': { type: 'ring', atk: [0, 6], needAtk: 46, job: 'warrior' }, // 佩戴要求：最大攻击力≥46（非等级要求）
  '泰坦戒指': { type: 'ring', sc: [0, 5], level: 24, job: 'taoist' },
  '紫碧螺': { type: 'ring', mc: [0, 5], level: 24, job: 'mage' },
  '五玄戒指': { type: 'ring', magDef: [0, 2], mc: [1, 3], level: 34, job: 'all' },
  '骷髅戒指': { type: 'ring', atk: [0, 3], sc: [0, 1], level: 30, job: 'all' },
  '狂风戒指': { type: 'ring', atk: [1, 2], level: 12, job: 'all' },
  '祈祷戒指': { type: 'ring', mc: [1, 5], level: 15, job: 'mage' },
  '魅力戒指': { type: 'ring', mc: [1, 2], level: 23, job: 'mage' },
  '道德戒指': { type: 'ring', sc: [1, 2], level: 23, job: 'taoist' },
  '圣战戒指': { type: 'ring', atk: [0, 7], magDef: [0, 1], level: 40, job: 'warrior' },
  '法神戒指': { type: 'ring', mc: [1, 6], magDef: [0, 1], level: 28, job: 'mage' },
  '天尊戒指': { type: 'ring', sc: [2, 7], magDef: [0, 1], level: 25, job: 'taoist' },
  // 特殊戒指
  '麻痹戒指': { type: 'ring', atk: [0, 1], level: 16, job: 'all', special: '麻痹' },
  '护身戒指': { type: 'ring', def: [0, 1], level: 16, job: 'all', special: '护身' },
  '传送戒指': { type: 'ring', level: 12, job: 'all', special: '传送' },
  '复活戒指': { type: 'ring', def: [0, 1], magDef: [0, 1], level: 16, job: 'all', special: '复活' },
  '火焰戒指': { type: 'ring', mc: [1, 2], level: 16, job: 'all', special: '火焰' },
  '超负载戒指': { type: 'ring', atk: [0, 1], level: 16, job: 'all', special: '超负载' },
  '防御戒指': { type: 'ring', sc: [1, 2], level: 16, job: 'all', special: '防御' },
  '记忆戒指': { type: 'ring', sc: [1, 3], level: 26, job: 'all', special: '记忆' },
  '魔血戒指': { type: 'ring', atk: [1, 3], level: 33, job: 'all' },
  '虹魔戒指': { type: 'ring', atk: [2, 2], level: 33, job: 'all', special: '吸血' },
  // === 鞋子 ===
  '鹿皮靴': { type: 'boots', level: 14, job: 'all' },
  '紫绸靴': { type: 'boots', def: [0, 1], level: 19, job: 'all' },
  '避魂靴': { type: 'boots', level: 24, job: 'all' },
  '赤燐鞋': { type: 'boots', level: 40, job: 'all' },
  '龙行鞋': { type: 'boots', def: [0, 2], level: 32, job: 'all' },
  // === 腰带 ===
  '铁腰带': { type: 'belt', def: [0, 1], magDef: [0, 1], level: 16, job: 'all' },
  '青铜腰带': { type: 'belt', def: [1, 1], level: 18, job: 'all' },
  '钢铁腰带': { type: 'belt', def: [1, 2], level: 23, job: 'all' },
  '金刚腰带': { type: 'belt', def: [1, 3], level: 39, job: 'all' },
  '黄金腰带': { type: 'belt', def: [1, 1], magDef: [0, 2], level: 31, job: 'all' },
  // === 宝玉 ===
  '勇猛宝玉': { type: 'jade', atk: [0, 1], level: 16, job: 'warrior' },
  '魔性宝玉': { type: 'jade', mc: [0, 1], level: 16, job: 'mage' },
  '仙界宝玉': { type: 'jade', sc: [0, 1], level: 16, job: 'taoist' },
  '守护宝玉': { type: 'jade', def: [0, 1], level: 16, job: 'all' },
  '制魔宝玉': { type: 'jade', magDef: [0, 1], level: 16, job: 'all' },
  '集中宝玉': { type: 'jade', def: [0, 1], level: 16, job: 'all' },
  // === 药品 ===
  '金创药(小量)': { type: 'potion', healHp: 30, price: 50 },
  '金创药(中量)': { type: 'potion', healHp: 60, price: 100 },
  '金创药(大量)': { type: 'potion', healHp: 100, price: 200 },
  '强效金创药': { type: 'potion', healHp: 200, price: 500 },
  '金创药(特量)': { type: 'potion', healHp: 400, price: 1000 },
  '魔法药(小量)': { type: 'potion', healMp: 30, price: 50 },
  '魔法药(中量)': { type: 'potion', healMp: 60, price: 100 },
  '魔法药(大量)': { type: 'potion', healMp: 100, price: 200 },
  '强效魔法药': { type: 'potion', healMp: 200, price: 500 },
  '魔法药(特量)': { type: 'potion', healMp: 400, price: 1000 },
  '太阳水': { type: 'potion', healHp: 100, healMp: 50, price: 500 },
  '强效太阳水': { type: 'potion', healHp: 200, healMp: 100, price: 1000 },
  '万年雪霜': { type: 'potion', healHp: 150, healMp: 250, price: 2500 },
  // === 材料 ===
  '龙鳞': { type: 'material', price: 1000 },
  '祝福油': { type: 'material', price: 1000 }, // 铁匠铺武器幸运强化材料
  // === 技能书 - 战士 ===
  '基本剑术': { type: 'skillbook', skill: '基本剑术', job: 'warrior', level: 7 },
  '攻杀剑术': { type: 'skillbook', skill: '攻杀剑术', job: 'warrior', level: 15 },
  '刺杀剑术': { type: 'skillbook', skill: '刺杀剑术', job: 'warrior', level: 22 },
  '半月弯刀': { type: 'skillbook', skill: '半月弯刀', job: 'warrior', level: 26 },
  '野蛮冲撞': { type: 'skillbook', skill: '野蛮冲撞', job: 'warrior', level: 30 },
  '雷霆剑法': { type: 'skillbook', skill: '雷霆剑法', job: 'warrior', level: 32 },
  '烈火剑法': { type: 'skillbook', skill: '烈火剑法', job: 'warrior', level: 35 },
  '狮子吼': { type: 'skillbook', skill: '狮子吼', job: 'warrior', level: 36 },
  '双龙斩': { type: 'skillbook', skill: '双龙斩', job: 'warrior', level: 38 },
  '龙影剑法': { type: 'skillbook', skill: '龙影剑法', job: 'warrior', level: 38 },
  '擒龙手': { type: 'skillbook', skill: '擒龙手', job: 'warrior', level: 32 },
  '护身气幕': { type: 'skillbook', skill: '护身气幕', job: 'warrior', level: 39 },
  '剑气爆': { type: 'skillbook', skill: '剑气爆', job: 'warrior', level: 44 },
  '天务': { type: 'skillbook', skill: '天务', job: 'warrior', level: 47 },
  '逐日剑法': { type: 'skillbook', skill: '逐日剑法', job: 'warrior', level: 50 },
  // === 技能书 - 法师 ===
  '火球术': { type: 'skillbook', skill: '火球术', job: 'mage', level: 7 },
  '抗拒火环': { type: 'skillbook', skill: '抗拒火环', job: 'mage', level: 12 },
  '诱惑之光': { type: 'skillbook', skill: '诱惑之光', job: 'mage', level: 13 },
  '大火球': { type: 'skillbook', skill: '大火球', job: 'mage', level: 15 },
  '地狱火': { type: 'skillbook', skill: '地狱火', job: 'mage', level: 16 },
  '雷电术': { type: 'skillbook', skill: '雷电术', job: 'mage', level: 17 },
  '瞬息移动': { type: 'skillbook', skill: '瞬息移动', job: 'mage', level: 19 },
  '爆裂火焰': { type: 'skillbook', skill: '爆裂火焰', job: 'mage', level: 22 },
  '火墙': { type: 'skillbook', skill: '火墙', job: 'mage', level: 24 },
  '疾光电影': { type: 'skillbook', skill: '疾光电影', job: 'mage', level: 26 },
  '寒冰掌': { type: 'skillbook', skill: '寒冰掌', job: 'mage', level: 28 },
  '地狱雷光': { type: 'skillbook', skill: '地狱雷光', job: 'mage', level: 30 },
  '魔法盾': { type: 'skillbook', skill: '魔法盾', job: 'mage', level: 31 },
  '圣言术': { type: 'skillbook', skill: '圣言术', job: 'mage', level: 32 },
  '嗜血术': { type: 'skillbook', skill: '嗜血术', job: 'mage', level: 33 },
  '冰咆哮': { type: 'skillbook', skill: '冰咆哮', job: 'mage', level: 35 },
  '灭天火': { type: 'skillbook', skill: '灭天火', job: 'mage', level: 38 },
  '分身术': { type: 'skillbook', skill: '分身术', job: 'mage', level: 41 },
  '火龙气焰': { type: 'skillbook', skill: '火龙气焰', job: 'mage', level: 42 },
  '天霜冰环': { type: 'skillbook', skill: '天霜冰环', job: 'mage', level: 44 },
  '深延术': { type: 'skillbook', skill: '深延术', job: 'mage', level: 47 },
  '流星火雨': { type: 'skillbook', skill: '流星火雨', job: 'mage', level: 49 },
  '冰焰术': { type: 'skillbook', skill: '冰焰术', job: 'mage', level: 53 },
  // === 技能书 - 道士 ===
  '治愈术': { type: 'skillbook', skill: '治愈术', job: 'taoist', level: 7 },
  '精神力战法': { type: 'skillbook', skill: '精神力战法', job: 'taoist', level: 9 },
  '施毒术': { type: 'skillbook', skill: '施毒术', job: 'taoist', level: 14 },
  '灵魂火符': { type: 'skillbook', skill: '灵魂火符', job: 'taoist', level: 18 },
  '召唤骷髅': { type: 'skillbook', skill: '召唤骷髅', job: 'taoist', level: 19 },
  '隐身术': { type: 'skillbook', skill: '隐身术', job: 'taoist', level: 20 },
  '集体隐身术': { type: 'skillbook', skill: '集体隐身术', job: 'taoist', level: 21 },
  '幽灵盾': { type: 'skillbook', skill: '幽灵盾', job: 'taoist', level: 22 },
  '心灵启示': { type: 'skillbook', skill: '心灵启示', job: 'taoist', level: 23 },
  '神圣战甲术': { type: 'skillbook', skill: '神圣战甲术', job: 'taoist', level: 25 },
  '气功波': { type: 'skillbook', skill: '气功波', job: 'taoist', level: 27 },
  '困魔咒': { type: 'skillbook', skill: '困魔咒', job: 'taoist', level: 28 },
  '净化术': { type: 'skillbook', skill: '净化术', job: 'taoist', level: 30 },
  '群体治愈术': { type: 'skillbook', skill: '群体治愈术', job: 'taoist', level: 31 },
  '无极真气': { type: 'skillbook', skill: '无极真气', job: 'taoist', level: 33 },
  '召唤神兽': { type: 'skillbook', skill: '召唤神兽', job: 'taoist', level: 35 },
  '召唤月灵': { type: 'skillbook', skill: '召唤月灵', job: 'taoist', level: 38 },
  '诅咒术': { type: 'skillbook', skill: '诅咒术', job: 'taoist', level: 40 },
  '瘟疫': { type: 'skillbook', skill: '瘟疫', job: 'taoist', level: 42 },
  '毒云': { type: 'skillbook', skill: '毒云', job: 'taoist', level: 43 },
  '血龙水': { type: 'skillbook', skill: '血龙水', job: 'taoist', level: 45 },
  '阴阳盾': { type: 'skillbook', skill: '阴阳盾', job: 'taoist', level: 30 },

  // ==================== 二大陆（遮天篇）装备 ====================
  // 数值口径见 二大陆计划表.html §四：同档位三职业数值对齐，防具 def 与 magDef 同值
  // --- T1 基础首饰补缺（Lv40-46，atk/mc/sc [1,4]）---
  '黑檀项链': { type: 'necklace', sc: [1, 3], level: 40, job: 'taoist' },
  '躲避项链': { type: 'necklace', def: [1, 2], level: 40, job: 'all' },
  // --- T3 补缺（Lv46-55，atk/mc/sc [4,10]）---
  '光芒项链': { type: 'necklace', mc: [2, 7], level: 46, job: 'mage' },
  '光芒手镯': { type: 'bracelet', mc: [1, 5], level: 46, job: 'mage' },
  '光芒戒指': { type: 'ring', mc: [1, 5], level: 46, job: 'mage' },
  '战神戒指': { type: 'ring', atk: [2, 6], level: 48, job: 'warrior' },
  '邪恶头冠': { type: 'helmet', def: [4, 6], magDef: [4, 6], atk: [1, 3], level: 50, job: 'warrior' },
  '太阳头盔': { type: 'helmet', def: [4, 7], magDef: [4, 5], level: 50, job: 'all' },
  '凤者之冠': { type: 'helmet', def: [4, 6], magDef: [4, 6], sc: [1, 3], level: 50, job: 'taoist' },
  // --- T4 考斯/命运/迪斯 + 藤域/木域/神域套（Lv50-60，atk/mc/sc [6,14]）---
  '考斯项链': { type: 'necklace', atk: [3, 8], level: 50, job: 'warrior' },
  '命运之链': { type: 'necklace', mc: [3, 9], level: 50, job: 'mage' },
  '迪斯项链': { type: 'necklace', sc: [3, 9], level: 50, job: 'taoist' },
  '藤域项链': { type: 'necklace', atk: [4, 10], level: 54, job: 'warrior' },
  '藤域手镯': { type: 'bracelet', atk: [3, 8], def: [1, 3], level: 54, job: 'warrior' },
  '藤域戒指': { type: 'ring', atk: [3, 9], level: 54, job: 'warrior' },
  '木域项链': { type: 'necklace', mc: [4, 10], level: 54, job: 'mage' },
  '木域手镯': { type: 'bracelet', mc: [3, 8], def: [1, 3], level: 54, job: 'mage' },
  '木域戒指': { type: 'ring', mc: [3, 9], level: 54, job: 'mage' },
  '神域项链': { type: 'necklace', sc: [4, 10], level: 54, job: 'taoist' },
  '神域手镯': { type: 'bracelet', sc: [3, 8], def: [1, 3], level: 54, job: 'taoist' },
  '神域戒指': { type: 'ring', sc: [3, 9], level: 54, job: 'taoist' },
  // --- 喋血系列（R4 蚁国产出）---
  '喋血战刃': { type: 'weapon', atk: [15, 40], level: 50, job: 'warrior', special: '连击' },
  '喋血魔杖': { type: 'weapon', mc: [15, 40], level: 50, job: 'mage' },
  '喋血道剑': { type: 'weapon', sc: [15, 40], level: 50, job: 'taoist' },
  // --- T5 盔甲/武器/蝴蝶套（Lv52-65，武器 atk/mc/sc [18,48]，防具 def [10,16]）---
  '覆云战衣': { type: 'armor', def: [10, 16], magDef: [10, 16], level: 52, job: 'warrior' },
  '古迹战甲': { type: 'armor', def: [10, 16], magDef: [10, 16], level: 52, job: 'mage' },
  '墨龙之翼': { type: 'armor', def: [10, 16], magDef: [10, 16], level: 52, job: 'taoist' },
  '墨龙之羽': { type: 'armor', def: [11, 16], magDef: [11, 16], level: 55, job: 'taoist' },
  '白虎战甲': { type: 'armor', def: [12, 16], magDef: [12, 16], level: 55, job: 'warrior' },
  '朱雀魔袍': { type: 'armor', def: [12, 16], magDef: [12, 16], level: 55, job: 'mage' },
  '青龙道衣': { type: 'armor', def: [12, 16], magDef: [12, 16], level: 55, job: 'taoist' },
  '嗜血战斧': { type: 'weapon', atk: [18, 48], level: 52, job: 'warrior', special: '吸血' },
  '嗜血法杖': { type: 'weapon', mc: [18, 48], level: 52, job: 'mage' },
  '嗜血圣剑': { type: 'weapon', sc: [18, 48], level: 52, job: 'taoist' },
  '蝴蝶战盔': { type: 'helmet', def: [8, 12], magDef: [8, 12], level: 56, job: 'warrior' },
  '蝴蝶法冠': { type: 'helmet', def: [8, 12], magDef: [8, 12], level: 56, job: 'mage' },
  '蝴蝶道冠': { type: 'helmet', def: [8, 12], magDef: [8, 12], level: 56, job: 'taoist' },
  '蝴蝶战链': { type: 'necklace', atk: [5, 12], level: 56, job: 'warrior' },
  '蝴蝶法链': { type: 'necklace', mc: [5, 12], level: 56, job: 'mage' },
  '蝴蝶道链': { type: 'necklace', sc: [5, 12], level: 56, job: 'taoist' },
  '蝴蝶战镯': { type: 'bracelet', atk: [4, 10], level: 56, job: 'warrior' },
  '蝴蝶法镯': { type: 'bracelet', mc: [4, 10], level: 56, job: 'mage' },
  '蝴蝶道镯': { type: 'bracelet', sc: [4, 10], level: 56, job: 'taoist' },
  '蝴蝶战戒': { type: 'ring', atk: [4, 10], level: 56, job: 'warrior' },
  '蝴蝶法戒': { type: 'ring', mc: [4, 10], level: 56, job: 'mage' },
  '蝴蝶道戒': { type: 'ring', sc: [4, 10], level: 56, job: 'taoist' },
  // --- T6 屠龙三系/骑甲/蝴蝶武器（Lv58-72，武器 atk/mc/sc [22,62]）---
  '圣战屠龙': { type: 'weapon', atk: [24, 62], level: 60, job: 'warrior' },
  '法神天魔': { type: 'weapon', mc: [24, 62], level: 60, job: 'mage' },
  '天尊圣纹': { type: 'weapon', sc: [24, 62], level: 60, job: 'taoist' },
  '骑甲': { type: 'armor', def: [12, 20], magDef: [12, 20], level: 60, job: 'all' },
  '蝴蝶战刃': { type: 'weapon', atk: [22, 58], level: 58, job: 'warrior' },
  '蝴蝶权杖': { type: 'weapon', mc: [22, 58], level: 58, job: 'mage' },
  '蝴蝶之扇': { type: 'weapon', sc: [22, 58], level: 58, job: 'taoist' },
  '潘夜隐戒': { type: 'ring', atk: [2, 5], mc: [2, 5], sc: [2, 5], level: 58, job: 'all' },
  '隐身戒指': { type: 'ring', def: [2, 4], magDef: [2, 4], level: 58, job: 'all' },
  // --- T7 遮天套/黄金系/葬神/天晶武器（Lv65-85，武器 atk/mc/sc [32,85]，防具 def [16,28]）---
  '遮天盔甲': { type: 'armor', def: [16, 28], magDef: [16, 28], level: 65, job: 'warrior' },
  '遮天法袍': { type: 'armor', def: [16, 28], magDef: [16, 28], level: 65, job: 'mage' },
  '遮天圣衣': { type: 'armor', def: [16, 28], magDef: [16, 28], level: 65, job: 'taoist' },
  '蝴蝶戒指': { type: 'ring', atk: [6, 14], level: 64, job: 'warrior' },
  '黄金戒指': { type: 'ring', atk: [7, 15], level: 75, job: 'warrior' },
  '黄金锏': { type: 'weapon', atk: [32, 80], level: 78, job: 'warrior' },
  '黄金剑': { type: 'weapon', sc: [32, 80], level: 78, job: 'taoist' },
  '黄金月': { type: 'weapon', mc: [32, 80], level: 78, job: 'mage' },
  '黄金盔甲': { type: 'armor', def: [20, 30], magDef: [20, 30], level: 78, job: 'warrior' },
  '黄金法袍': { type: 'armor', def: [20, 30], magDef: [20, 30], level: 78, job: 'mage' },
  '黄金圣衣': { type: 'armor', def: [20, 30], magDef: [20, 30], level: 78, job: 'taoist' },
  '葬神头盔': { type: 'helmet', def: [16, 24], magDef: [16, 24], level: 72, job: 'all' },
  '暴君吊坠': { type: 'necklace', atk: [8, 18], mc: [8, 18], sc: [8, 18], level: 70, job: 'all' },
  '天晶战刃': { type: 'weapon', atk: [34, 85], level: 80, job: 'warrior' },
  '虎魄之剑': { type: 'weapon', sc: [34, 85], level: 80, job: 'taoist' },
  '太虚圣刀': { type: 'weapon', mc: [34, 85], level: 80, job: 'mage' },
  '战力无双': { type: 'ring', atk: [9, 18], level: 82, job: 'warrior' },
  '道临天下': { type: 'necklace', sc: [9, 18], def: [4, 8], level: 82, job: 'taoist' },
  // --- T8 传说档（Lv75-90，atk/mc/sc [36,60]）---
  '麒麟臂(神)': { type: 'bracelet', atk: [12, 22], mc: [12, 22], level: 85, job: 'all' },
  '麒麟臂(尊)': { type: 'bracelet', sc: [12, 22], def: [6, 12], level: 85, job: 'all' },
  '火龙之心': { type: 'ring', atk: [10, 20], mc: [10, 20], sc: [10, 20], level: 86, job: 'all' },
  '遮天左手': { type: 'bracelet', atk: [14, 24], level: 84, job: 'warrior' },
  '遮天右手': { type: 'bracelet', mc: [14, 24], level: 84, job: 'mage' },
  '苍茫神翼': { type: 'armor', def: [22, 36], magDef: [22, 36], level: 84, job: 'all' },
  '苍茫神石': { type: 'jade', atk: [8, 16], mc: [8, 16], sc: [8, 16], level: 84, job: 'all' },
  '遮天神石': { type: 'jade', atk: [10, 18], mc: [10, 18], sc: [10, 18], level: 86, job: 'all' },
  '逆火麻痹': { type: 'ring', atk: [4, 8], level: 80, job: 'all', special: '麻痹' },
  '护身精灵': { type: 'ring', def: [4, 8], magDef: [4, 8], level: 80, job: 'all', special: '护身' },
  '永生指环': { type: 'ring', def: [2, 6], magDef: [2, 6], level: 80, job: 'all', special: '复活' },
  // --- 腰带/靴补缺（诺玛三王/冥王产出）---
  '霸者腰带': { type: 'belt', def: [6, 12], magDef: [4, 8], level: 56, job: 'warrior' },
  '邪者腰带': { type: 'belt', def: [5, 10], magDef: [5, 10], level: 56, job: 'mage' },
  '道者腰带': { type: 'belt', def: [5, 10], magDef: [5, 10], level: 56, job: 'taoist' },
  '布靴': { type: 'boots', def: [2, 5], level: 56, job: 'all' },
};
